TTT-2/TTT2

gamemodes/terrortown/gamemode/cl_hud.lua
Sollte so wieder als traitor richtig angezeigt werden
=> Fixed wrong time display on hastemode

gamemodes/terrortown/gamemode/voice.lua
VoiceChat funktioniert nun wieder einwandfrei
=> Fixed VoiceChat

gamemodes/terrortown/gamemode/admin.lua, gamemodes/terrortown/gamemode/cl_scoring_events.lua, gamemodes/terrortown/gamemode/cl_targetid.lua, gamemodes/terrortown/gamemode/karma.lua, gamemodes/terrortown/gamemode/lang/chef.lua, gamemodes/terrortown/gamemode/player.lua, gamemodes/terrortown/gamemode/shared.lua, gamemodes/terrortown/gamemode/vgui/sb_main.lua
=> Revert "Cleanup 1"

gamemodes/terrortown/gamemode/init.lua
=> Adding autoslay

gamemodes/terrortown/gamemode/cl_credits_main.lua
• Changed my nickname. (I prefer to use «Satton(RU)» instead of Satton2 but Github doesn't like brackets)
• Added my Steam profile link.
Also, thank you @Alf21 for adding me to this list. ;)
=> Minor changes in credits file.

gamemodes/terrortown/gamemode/server/sv_corpse.lua
- e.g. through Fake Body/Dead Ringer etc.
=> Add alive check for corpse so player only get revealed when they are dead

gamemodes/terrortown/gamemode/client/cl_help.lua, gamemodes/terrortown/gamemode/shared/sh_sprint.lua, lua/bind/cl_init.lua
A liitle QOL change which adds binding categories. Its still possible to not set a category - these bindings will be added to Other Bindings.
=> Settings Binding Categories

gamemodes/terrortown/gamemode/client/cl_hud_manager.lua, gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/hud_element_base/cl_init.lua, gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/pure_skin_element.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttdrowning/pure_skin_drowning.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/pure_skin_playerinfo.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttitemhuddisplay/pure_skin_items.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttmstack/pure_skin_mstack.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttpunchometer/pure_skin_punchometer.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttroundinfo/pure_skin_roundinfo.lua, gamemodes/terrortown/gamemode/shared/hud_elements/ttttarget/pure_skin_target.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttwswitch/pure_skin_wswitch.lua, gamemodes/terrortown/gamemode/shared/huds/pure_skin/cl_init.lua
=> Advanced Resizing with Font Resizing

gamemodes/terrortown/gamemode/client/cl_equip.lua, gamemodes/terrortown/gamemode/client/cl_shopeditor.lua, gamemodes/terrortown/gamemode/server/sv_shop.lua, gamemodes/terrortown/gamemode/shared/sh_equip_items.lua
* added "reroll after every buy feature"
* improved "Shopeditor Option" design
* implemented Team rerolling (very good together with reroll after buy :D)
=> Improved Random Shop

gamemodes/terrortown/gamemode/client/cl_lang.lua, gamemodes/terrortown/gamemode/client/cl_tips.lua
this fixes a bug which caused the hud to not render for some people when damagelogs were installed
=> fixed hud bug (#331)

gamemodes/terrortown/gamemode/server/sv_weaponry.lua
* support for Crowbar replacements like lightsaber and fists by accessing the WEAPON_MELEE kind.
=> Implemented a ConVar for the shove cooldown of the crowbar

gamemodes/terrortown/gamemode/client/cl_fonts.lua, gamemodes/terrortown/gamemode/client/cl_main.lua, gamemodes/terrortown/gamemode/client/vgui/cl_hudswitcher.lua, gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/pure_skin_element.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/pure_skin_playerinfo.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttmstack/pure_skin_mstack.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttpunchometer/pure_skin_punchometer.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttroundinfo/pure_skin_roundinfo.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttsidebar/pure_skin_sidebar.lua, gamemodes/terrortown/gamemode/shared/hud_elements/ttttarget/pure_skin_target.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttwswitch/pure_skin_wswitch.lua, gamemodes/terrortown/gamemode/shared/huds/base_huds/scalable_hud/cl_init.lua, gamemodes/terrortown/gamemode/shared/huds/pure_skin/cl_init.lua, gamemodes/terrortown/gamemode/shared/sh_include.lua
* New Font Module which manages base functionality like ShadowedText and AdvancedText (scaled and shadowed)
* Font Mipmapping for AdancedText for better readibility on higher scales
* Moved HUDMODULE:AdvancedText and ShadowedText to the new module (important node: this will break addons (marker and killinfo atm) which used the functions)
=> Advanced Font System

gamemodes/terrortown/gamemode/server/sv_main.lua
You can now decide (with a hook) if the Message should even be shown for certain players and what players should be shown.
First of all this brings more possibilities into the game (for me for my BodyGuard :) ) and I think it's better if the hook is changeable PER player, and not only for all at once.
Please look over it and tell me what needs to be changed for you to accept it.
Oh, also the Spy needs to be updated if you accept this (I may do it if needed)
=> Changed TellTraitorsAboutTraitors function

gamemodes/terrortown/gamemode/shared/sh_sprint.lua
A shared hook that modifies sprint drain (and recovery).
=> Add StaminaMult Hook to sh_sprint.lua

gamemodes/terrortown/gamemode/shared/sh_sprint.lua
Untested yet, but made in comparison to TTTPlayerSpeedModifier.
=> Use extra modifier table to support multiple hooking

gamemodes/terrortown/gamemode/client/cl_radio.lua
Translation was not "setup" correctly.
=> Fixed translation errors

gamemodes/terrortown/gamemode/client/cl_shopeditor.lua, gamemodes/terrortown/gamemode/server/sv_main.lua, gamemodes/terrortown/gamemode/server/sv_player.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua
It's important to test whether the config files are loaded completely (before merging this).
=> Fixed a shopeditor bug and modified the old convar initialization

gamemodes/terrortown/entities/entities/ttt_c4/shared.lua, gamemodes/terrortown/entities/entities/ttt_decoy.lua, gamemodes/terrortown/entities/entities/ttt_health_station.lua, gamemodes/terrortown/entities/entities/ttt_radio.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua, gamemodes/terrortown/gamemode/client/cl_targetid.lua, gamemodes/terrortown/gamemode/shared/lang/english.lua, gamemodes/terrortown/gamemode/shared/lang/german.lua, lua/terrortown/entities/items/item_ttt_radar/init.lua
The microwave and the decoy got updated to work better with TTT2. This includes:
- the usage of the new targetID system
- fixing incompatibility with new role system
Some screenshots of the new targetID for these entities:
=> Added better TTT2 support for vanilla TTT items

gamemodes/terrortown/gamemode/shared/lang/english.lua
- Minor grammar fixes/edits.
- Removed the line «L.sb_sortby = "Sort By:"» because it already exists in the file.
=> Minor changes in the language file

gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua, gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua, gamemodes/terrortown/gamemode/client/cl_equip.lua, gamemodes/terrortown/gamemode/client/cl_keys.lua, gamemodes/terrortown/gamemode/client/cl_main.lua, gamemodes/terrortown/gamemode/client/cl_player_ext.lua, gamemodes/terrortown/gamemode/client/cl_tips.lua, gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua, gamemodes/terrortown/gamemode/client/vgui/cl_sb_team.lua, gamemodes/terrortown/gamemode/server/sv_gamemsg.lua, gamemodes/terrortown/gamemode/server/sv_karma.lua, gamemodes/terrortown/gamemode/server/sv_main.lua, gamemodes/terrortown/gamemode/server/sv_voice.lua, gamemodes/terrortown/gamemode/server/sv_weaponry.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttpunchometer/old_ttt_punchometer.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttpunchometer/pure_skin_punchometer.lua, gamemodes/terrortown/gamemode/shared/sh_lang.lua, lua/autorun/gs_crazyphysics.lua
This commit localizes convars, where possible.
=> Localize ConVars

gamemodes/terrortown/gamemode/client/cl_damage_indicator.lua, gamemodes/terrortown/gamemode/client/cl_help.lua, gamemodes/terrortown/gamemode/shared/lang/english.lua, gamemodes/terrortown/gamemode/shared/lang/german.lua, gamemodes/terrortown/gamemode/shared/sh_sprint.lua
=> Added client-convar to disable doubletap Sprinting

gamemodes/terrortown/gamemode/client/cl_keys.lua, gamemodes/terrortown/gamemode/client/cl_main.lua, gamemodes/terrortown/gamemode/server/sv_main.lua, gamemodes/terrortown/gamemode/shared/sh_main.lua, gamemodes/terrortown/gamemode/shared/sh_sprint.lua
You will automatically start regenerating stamina if you have zero stamina for some time (Currently 1.5 seconds) regardless if you are still pressing sprint / moving. It feels a lot more natural that way and prevents you from having to stop moving if the sprint was initiated by double tapping. I also removed the hooks to use the corresponding GM functions instead.
=> Stamina autoregen on exhaustion

gamemodes/terrortown/gamemode/client/cl_help.lua, gamemodes/terrortown/gamemode/client/cl_keys.lua, gamemodes/terrortown/gamemode/client/cl_voice.lua, gamemodes/terrortown/gamemode/client/cl_weapon_pickup.lua, gamemodes/terrortown/gamemode/server/sv_main.lua, gamemodes/terrortown/gamemode/server/sv_voice.lua, gamemodes/terrortown/gamemode/shared/lang/english.lua, gamemodes/terrortown/gamemode/shared/lang/german.lua, lua/bind/cl_init.lua
Add function to determine if F1 menu is open
Move MuteTeam to Net Library
Rename bind param of PlayerBindPress to bindName, since bind is reserved globally
Move voice binds to TTT2
Move RoleGlobalVoice to Net Library
Voice Overlay now respects sv_voiceenable
Add fallback to weaponswitch bind
Fix bind being triggered on assignment
Add IsPressed function for binds
Definitely requires some more testing
Fixes Issue #437
=> Move voice binds to TTT2 and various

gamemodes/terrortown/gamemode/shared/sh_sprint.lua
I think preventSprint was forgotten here, added it back
=> added preventSprint to doubletap feature

gamemodes/terrortown/gamemode/client/cl_main.lua, gamemodes/terrortown/gamemode/client/cl_voice.lua, gamemodes/terrortown/gamemode/server/sv_gamemsg.lua, gamemodes/terrortown/gamemode/server/sv_main.lua, gamemodes/terrortown/gamemode/server/sv_voice.lua, gamemodes/terrortown/gamemode/shared/sh_include.lua, gamemodes/terrortown/gamemode/shared/sh_voice.lua
I've reworked the audio hooks and cleaned up some elements
The hook `TTT2AvoidTeamVoiceChat` is now `TTT2CanSeeChat` since this hook had nothing todo with voice
Added the hook `TTT2CanHearVoiceChat` and modified `TTT2CanUseVoiceChat`
=> reworked audio hooks

gamemodes/terrortown/gamemode/client/cl_search.lua, gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua, gamemodes/terrortown/gamemode/server/sv_corpse.lua, gamemodes/terrortown/gamemode/server/sv_networking.lua, gamemodes/terrortown/gamemode/server/sv_player_ext.lua, gamemodes/terrortown/gamemode/shared/sh_player_ext.lua, lua/autorun/gs_crazyphysics.lua
This should fix the miniscoreboard issues.
=> TTT2NET: Transition body confirm to new synced data tables

gamemodes/terrortown/gamemode/shared/lang/polish.lua
TTT2 now supporting Polish language!
=> Added new language [PL]

gamemodes/terrortown/gamemode/shared/lang/polish.lua
L.body_found_t >>> L.body_found_traitor etc
=> Quick Fix To polish.lua

CHANGELOG.md
This is a changelog lazily compiled from the GitHub 'Releases' and from `cl_changes`.
This is a draft for now as there are still multiple things to discuss and change e.g.:
- Do we want to keep `New`, `Improved` and `Fixed` as our subsections?
- What about `Deprecated` and `Removed`?
- Do we want to rename `New` to `Added` and bring the subsections into alphabetical order?
- Do we want to restructure/rewrite the older changelog entries or leave them be?
- Do we want to remove some **bolds** ?
- Should we explicitly mention our versioning schema?
=> Streamlined Markdown Changelog

.gitignore, gamemodes/terrortown/gamemode/shared/sh_player_ext.lua, lua/includes/modules/roles.lua, lua/terrortown/entities/roles/ttt_role_base/shared.lua
Currently, there is no possibility to create an own abstract ROLE (because this still will be initialized like a normal ROLE)
=> Small ROLE improvements

gamemodes/terrortown/gamemode/server/sv_armor.lua
Added Convar to enable/disable the armor system handling headshots
=> Armor headshot handling

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_main.lua, gamemodes/terrortown/gamemode/server/sv_main.lua
As MR to **discuss** var naming (`GAMEMODE.roundCount`) and whether it's required
=> Added GAMEMODE.roundCount and cleaned GAMEMODE var usage

gamemodes/terrortown/gamemode/client/vgui/cl_sb_team.lua
* Removed `ipairs`
* Added some row validity checks
* Localized sorting function instead of recreating it every and every time again
=> Team sorting error fix

gamemodes/terrortown/gamemode/shared/lang/italian.lua
Uploaded the old file without the VGUI rework and the new strings translated, with some fixes.
=> New strings and fixes

CHANGELOG.md, gamemodes/terrortown/gamemode/shared/hud_elements/tttminiscoreboard/pure_skin_miniscoreboard.lua
Changed so players will stay in the miniscoreboard if they were active in round.
Fixed update delay not working.
=> Miniscoreboard fixes

lua/terrortown/entities/items/item_ttt_radar/cl_init.lua
fixed radar colors for undefined teams
=> fixed radar on client

gamemodes/terrortown/gamemode/server/sv_roleselection.lua
The roleselection will now properly consider the max roles and max base roles convars.
=> Fix max roles

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_roleselection.lua, gamemodes/terrortown/gamemode/shared/sh_door.lua
=> Roleselection: Fixed innocent subrole selection

CONTRIBUTING.md
Updated the contributing guidelines to provide definitive steps for contributors.
=> Meta: Updated contributing guidelines

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_addonchecker.lua, gamemodes/terrortown/gamemode/server/sv_main.lua
I cleaned up the whole addon checker file. This cleanup can also be used in preparation for a future web based database. Additionally I added missing addons to this list. A new command `addonchecker` was also added to get the output at any time.
=> AddonChecker: Reworked List and Cleanup

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_main.lua
Fix for [Issue 507](https://github.com/TTT-2/TTT2/issues/507)
=> ttt_round_end now gets reset when the map changes

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_corpse.lua
fix for [Issue 586](https://github.com/TTT-2/TTT2/issues/586)
=> fixed image in confirmation notification for corpses from bots

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_scoring.lua
=> Score panel: Fix column translation

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_player.lua
=> Gameplay: Players who disconnect now leave a corpse

CONTRIBUTING.md
I hope this is pretty self explanatory =D
=> Contributing: Added line regarding github conversations

.github/ISSUE_TEMPLATE/bug_report.md
Updated the outdated FAQ link and added a link to existing issues.
=> Issue template: Updated FAQ link, added existing issues link

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_eventpopup.lua
=> EPOP docs: Fixed wrong default value in epop docstring

gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
This patch adds our new VIP users. 
They are valuable members of the community and have earned their badge showing their commitment.
=> VIP: Add new VIP users

CHANGELOG.md, lua/autorun/client/b-draw_lib.lua
=> Fetch: changed a '*' to a '-'

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_equip.lua, gamemodes/terrortown/gamemode/shared/lang/english.lua, gamemodes/terrortown/gamemode/shared/lang/german.lua, gamemodes/terrortown/gamemode/shared/lang/italian.lua, gamemodes/terrortown/gamemode/shared/lang/polish.lua, gamemodes/terrortown/gamemode/shared/lang/russian.lua, gamemodes/terrortown/gamemode/shared/lang/simpchinese.lua, gamemodes/terrortown/gamemode/shared/lang/spanish.lua, lua/autorun/ttt_bem_autorun.lua
As I like ConVars and not everyone likes to buy Items by doubleclicking on them (or accidentally doubleclicks), I added this convar.
=> Shop: Added ConVar to toggle double-click buying

CHANGELOG.md
PR #602 added its change to the already released version, which is incorrect.
=> Changelog: Fix wrong position from PR #602

CHANGELOG.md, gamemodes/terrortown/gamemode/shared/sh_util.lua, lua/ttt2/extensions/table.lua
Added a useful utility function and made some improvements to existing util-functions.
=> Util functions: Added table.ExtractRandomEntry(tbl, filterFn)

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_changes.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua
Bumps the version number to v0.7.4b and adds the changelog ingame
=> Version: Bump to v0.7.4b & add changelog

CHANGELOG.md, lua/ttt2/libraries/targetid.lua
Now doesnt depend on earlier convar creation.
=> TargetID-Fix: Initializing convars later

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_player.lua
=> Player: Remove pointless notification

gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
@Histalek and @ZenBre4ker you earned it :rocket:
=> Badge: Added @Histalek as Dev and ZenBre4ker as VIP

.github/workflows/ci.yml
This will provide annotations to PRs.
See: https://github.com/FPtje/GLuaFixer/releases/tag/1.17.0 :tada:
=> Update glualint to 1.17.0

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_changes.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua
preperations for the 0.8.1b release
=> Update: Added changelog and bumped version number

gamemodes/terrortown/gamemode/shared/lang/ja.lua
there were some mistakes, so I fixed.
=> Updated Japanese Translation

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua, gamemodes/terrortown/gamemode/server/sv_weaponry.lua
Facepunch/garrysmod#1776 (by @Flapchik) and https://github.com/Facepunch/garrysmod/commit/9d3ba424fa943befc948a535efedaadc7e2540f5 (by @svdm)
=> Fixes: Added TTT fixes (gmod branch)

CHANGELOG.md, gamemodes/terrortown/terrortown.txt
https://wiki.facepunch.com/gmod/Gamemode_Creation#category
=> Gamemode: Added category from the upcoming update

gamemodes/terrortown/gamemode/shared/lang/ja.lua
=> Language: Fixed Japanese Translation

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_changes.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua
Bump version to v0.8.2b and added the ingame changelog.
This also adds myself to the GM.Author field and changed the unmaintained GM.Website to our documentation website as a stopgap measure.
=> [Release] Added changelog, bumped version and small GM-info fixes

CHANGELOG.md, RELEASE_PROCESS.md
This PR starts documenting our release workflow aiming to:
- prevent mistakes
- convey changes in our release process
- enable spotting problems
- enable proposing improvements
=> Meta: Document release process

gamemodes/terrortown/gamemode/server/sv_main.lua
This fixes the bug of an endless round (until time is up) even if no one is alive anymore (draw)
=> WIN_NONE: Fixed draw

CHANGELOG.md, gamemodes/terrortown/gamemode/shared/lang/pl.lua
I've added all the missing lines to the translation, everything should be okay, if something doesn't work, please contact me, I will fix it at the spot.
=> Added missing lines to pl.lua

CHANGELOG.md, lua/terrortown/menus/score/info.lua
By filtering scoreName and Positivity of the score, we can now show summarized events.
=> Roundendscreen: Summarize events

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_scoring.lua, gamemodes/terrortown/gamemode/server/sv_karma.lua, gamemodes/terrortown/gamemode/server/sv_main.lua, gamemodes/terrortown/gamemode/shared/events/base_event.lua, gamemodes/terrortown/gamemode/shared/events/finish.lua, gamemodes/terrortown/gamemode/shared/lang/de.lua, gamemodes/terrortown/gamemode/shared/lang/en.lua, gamemodes/terrortown/gamemode/shared/lang/es.lua, gamemodes/terrortown/gamemode/shared/lang/fr.lua, gamemodes/terrortown/gamemode/shared/lang/it.lua, gamemodes/terrortown/gamemode/shared/lang/ja.lua, gamemodes/terrortown/gamemode/shared/lang/pl.lua, gamemodes/terrortown/gamemode/shared/lang/ru.lua, gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua, lua/terrortown/menus/score/info.lua, lua/ttt2/libraries/eventdata.lua, lua/ttt2/libraries/events.lua
Okay, I reworked the karma now with the roundendscreen directly as target.
=> Karma: Store changes and show on roundenscreen

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_karma.lua, gamemodes/terrortown/gamemode/server/sv_main.lua
Fixed karma being applied to weapon damage even though karma is disabled: https://github.com/Facepunch/garrysmod/pull/1780
Fixed karma autokick evasion: https://github.com/Facepunch/garrysmod/pull/1803 (adapted from this PR)
=> Karma: Fixes autokick evasion and damage scaling

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_changes.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua
Increments the version number and adds the changelog to the game menu.
=> [Release] Preparation for 0.9.3b

CHANGELOG.md, gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
- added Sven to devs
- added Pytho to VIPs
=> Scoreboard: VIP and Dev Update

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_changes.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua
=> Release-0.11.0

lua/terrortown/entities/roles/ttt_role_base/shared.lua
Fixed a typo.
"geiven" to "given".
=> fixed typo

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_changes.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua
Just made this ready if you want....
=> Release 0.11.1

lua/ttt2/extensions/draw.lua, lua/ttt2/libraries/credits.lua
A few small things I noticed in the documentation that were wrong.
=> Docs: Fixes

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_changes.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua
Bump version number and add changelog.
=> Release: v0.11.4b

CHANGELOG.md, gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua, gamemodes/terrortown/gamemode/server/sv_main.lua, lua/terrortown/lang/de.lua, lua/terrortown/lang/en.lua, lua/terrortown/lang/es.lua, lua/terrortown/lang/fr.lua, lua/terrortown/lang/it.lua, lua/terrortown/lang/ja.lua, lua/terrortown/lang/pl.lua, lua/terrortown/lang/ru.lua, lua/terrortown/lang/zh_hans.lua, lua/terrortown/lang/zh_tw.lua, lua/terrortown/menus/gamemode/administration/roundsetup.lua
This PR adds a way to disable the round and time limits for a session.
=> Session limits: Added convar to disable session limits

lua/terrortown/lang/ru.lua
- Removed my forgoten comment.
- Fixed some  issues.
=> Small Russian localization update

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua, lua/ttt2/extensions/table.lua, lua/ttt2/libraries/entspawn.lua
The issue https://github.com/TTT-2/TTT2/issues/1005 has been resolved, and the fix is applied exclusively under the TTT2 game mode plugin.
=> Fixed an issue in `table.GetEqualEntryKeys` when nil is provided

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_corpse.lua
=> Corpse: fix effect_fn being permanent

CHANGELOG.md, gamemodes/terrortown/gamemode/shared/sh_shopeditor.lua, lua/terrortown/lang/de.lua, lua/terrortown/lang/en.lua, lua/terrortown/lang/es.lua, lua/terrortown/lang/fr.lua, lua/terrortown/lang/it.lua, lua/terrortown/lang/ja.lua, lua/terrortown/lang/pl.lua, lua/terrortown/lang/pt_br.lua, lua/terrortown/lang/ru.lua, lua/terrortown/lang/zh_hans.lua, lua/terrortown/lang/zh_tw.lua
a lot of throwables out there that don't go to the nade slot
=> override weapon `Kind` to allow changing equipment slots

CHANGELOG.md, lua/terrortown/menus/gamemode/equipment.lua, lua/terrortown/menus/gamemode/equipment/base_equipment.lua, lua/terrortown/menus/gamemode/roles.lua, lua/terrortown/menus/gamemode/roles/base_roles.lua
=> allow extending item/role menus without detouring as much

gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
added EntranceJew to the in-game VIP list
=> [VIP] added EntranceJew

gamemodes/terrortown/gamemode/client/cl_shopeditor.lua, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dpanel_ttt2.lua, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenubutton_ttt2.lua, gamemodes/terrortown/gamemode/server/sv_networking.lua, gamemodes/terrortown/gamemode/server/sv_weaponry.lua, gamemodes/terrortown/gamemode/shared/sh_decal.lua, gamemodes/terrortown/gamemode/shared/sh_equip_items.lua
Also 'Doublicated' was bugging me, so i fixed that too.
=> docs: Fix partial docstrings

CHANGELOG.md, gamemodes/terrortown/entities/entities/ttt_flame.lua, gamemodes/terrortown/entities/entities/ttt_hat_deerstalker.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua
the entities are from upstream but with mild changes to fit
=> entity bringdown

gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua, gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
This commit removes the last usages of `DTVar()` in our code and replaces them with `NetworkVar()`.
This also replaces direct access to `self.dt.var` with their respective accessors.
Another thing to mention is that zm_carry was using two network bools in the same "slot". I have no idea what the implications of this were. It is fixed now.
=> fix: Remove usage of `DTVar()`

lua/terrortown/lang/de.lua, lua/terrortown/lang/es.lua, lua/terrortown/lang/fr.lua, lua/terrortown/lang/it.lua, lua/terrortown/lang/ja.lua, lua/terrortown/lang/pl.lua, lua/terrortown/lang/pt_br.lua, lua/terrortown/lang/ru.lua, lua/terrortown/lang/zh_hans.lua, lua/terrortown/lang/zh_tw.lua
Cleaned up language file with new auto cleanup tool: https://github.com/TTT-2/ttt2-language_parser
=> [Language] Cleanup

lua/terrortown/lang/de.lua, lua/terrortown/lang/en.lua, lua/terrortown/lang/es.lua, lua/terrortown/lang/fr.lua, lua/terrortown/lang/it.lua, lua/terrortown/lang/ja.lua, lua/terrortown/lang/pl.lua, lua/terrortown/lang/pt_br.lua, lua/terrortown/lang/ru.lua, lua/terrortown/lang/sv.lua, lua/terrortown/lang/uk.lua, lua/terrortown/lang/zh_hans.lua, lua/terrortown/lang/zh_tw.lua, lua/terrortown/menus/gamemode/gameplay/general.lua, lua/terrortown/menus/gamemode/gameplay/voiceandvolume.lua
=> [Feature] voice and volume menu

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua
This adds database access to checkbox, slider and the combobox
=> VGUI: Add Database access to panel elements

gamemodes/terrortown/entities/entities/ttt_c4/shared.lua, gamemodes/terrortown/gamemode/client/cl_targetid.lua, gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsearchbar_ttt2.lua, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenubutton_ttt2.lua, gamemodes/terrortown/gamemode/server/sv_player.lua, gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
Still needs some work. Inline comments where i wasn't sure what to do.
=> fix: More undefined var fixes

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua, gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dtextentry_ttt2.lua, lua/terrortown/menus/gamemode/administration/playermodels.lua
@ZenBre4ker Is that what you said, and is there anywhere else?
=> Fix nil values for "dcombobox", "playermodels", "dcombobox_ttt2

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
merged this fix into TTT2: https://github.com/Facepunch/garrysmod/pull/2023
=> Upstream update

gamemodes/terrortown/gamemode/server/sv_player_ext.lua, gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
=> Sprint: Fix stamina start value

CHANGELOG.md, lua/ttt2/libraries/bodysearch.lua
added a check if the variable is set before accessing it
=> StartAng: Make sure angle is defined before accessing

CHANGELOG.md, lua/ttt2/libraries/bodysearch.lua
the dete call HUD was invisible due to a wrong variable being accessed
=> Fix dete call HUD

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_changes.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua
=> release: prepare v0.12.1b

CHANGELOG.md, lua/ttt2/libraries/bodysearch.lua
=> Fixed water level icon name

CHANGELOG.md, gamemodes/terrortown/entities/entities/ttt_flame.lua, gamemodes/terrortown/entities/entities/ttt_traitor_button/shared.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua, gamemodes/terrortown/entities/weapons/weapon_tttbase.lua, gamemodes/terrortown/gamemode/client/cl_voice.lua, gamemodes/terrortown/gamemode/server/sv_addonchecker.lua, gamemodes/terrortown/gamemode/server/sv_main.lua, gamemodes/terrortown/gamemode/shared/sh_door.lua, lua/ttt2/libraries/hudelements.lua, lua/ttt2/libraries/huds.lua, lua/ttt2/libraries/items.lua, lua/ttt2/libraries/orm.lua
The lua Server mentioned many globals that were unused, but it seems that they are just misspelled variables in most cases.
THis is untested and is just a theoretical fix. So gotta look what could be wrong now.
=> Lua-Server: Fix hidden bugs

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
=> Binoculars: fix changing zoom level interrupts scan

.github/ISSUE_TEMPLATE/feature_request.md
Was bugging me when making issues
=> Issue template: Update Feature request template to use headings

CHANGELOG.md, lua/terrortown/lang/tr.lua
- Added New Lines
- Fixed Context
=> Updated Turkish Language

CHANGELOG.md, lua/terrortown/menus/gamemode/administration/roundsetup.lua
=> now we know what the dete combobox does (fixes #1175)

CHANGELOG.md, lua/terrortown/lang/tr.lua
- Added New Beacon Text
- Various Changes To Some Text
=> Lang: Added New Lines

lua/terrortown/lang/de.lua, lua/terrortown/lang/en.lua, lua/terrortown/lang/es.lua, lua/terrortown/lang/fr.lua, lua/terrortown/lang/it.lua, lua/terrortown/lang/ja.lua, lua/terrortown/lang/pl.lua, lua/terrortown/lang/pt_br.lua, lua/terrortown/lang/ru.lua, lua/terrortown/lang/sv.lua, lua/terrortown/lang/tr.lua, lua/terrortown/lang/uk.lua, lua/terrortown/lang/zh_hans.lua, lua/terrortown/lang/zh_tw.lua
fixes #1193 
While refactoring the code this one got lost somewhere.
=> Fixed Misnamed Language Identitifer

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_tttbase.lua, gamemodes/terrortown/gamemode/server/sv_corpse.lua, lua/ttt2/libraries/bodysearch.lua
=> fix invalid dmginfo being invalid (mitigates #1230)

CHANGELOG.md, lua/terrortown/lang/tr.lua
=> Updated Turkish Localization

CHANGELOG.md, lua/terrortown/lang/de.lua, lua/terrortown/lang/en.lua, lua/terrortown/lang/es.lua, lua/terrortown/lang/fr.lua, lua/terrortown/lang/it.lua, lua/terrortown/lang/ja.lua, lua/terrortown/lang/pl.lua, lua/terrortown/lang/pt_br.lua, lua/terrortown/lang/ru.lua, lua/terrortown/lang/sv.lua, lua/terrortown/lang/tr.lua, lua/terrortown/lang/uk.lua, lua/terrortown/lang/zh_hans.lua, lua/terrortown/lang/zh_tw.lua, lua/terrortown/menus/gamemode/equipment/base_equipment.lua
=> describe damage scaling (fixes #1059)

CHANGELOG.md, lua/ttt2/libraries/database.lua
Fixed a local variable being global that breaks PointShop 2
=> Global callback fix

gamemodes/terrortown/gamemode/server/sv_voice.lua
Based on the discussion in #1263 I noticed that this convar has a missing on change callback. I added it.
(It is untested, but should do the trick)
=> sv_voiceenable: Added OnChange callback

CHANGELOG.md, lua/ttt2/libraries/bodysearch.lua
Added a check for a public policing search
=> Fixed Last Seen Entity

lua/autorun/server/ttt2_force_download.lua
fixes the issue in which there are icons sometimes but actually there are not icons because there are is not the anti icons of having them, paradoxically not really icons
=> Icons: Fix missing icons

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_defuser.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_health_station.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_teleport.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_unarmed.lua, gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
- the Deploy() code is useless
- the DrawViewModel check happens each DrawHUD so it's pointless to set it once in Deploy
- the only reason it appeared to work is because the FOV of those items were set to something incredibly small
=> SWEP: Add SWEP.InvisibleViewModel

gamemodes/terrortown/entities/entities/ttt_firegrenade_proj.lua, gamemodes/terrortown/entities/entities/ttt_smokegrenade_proj.lua
=> Grenade: Fix grenade decals

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua, gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
le changelogged has le purpose
=> ClearHUDHelp

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_targetid.lua
=> HUD: Scaling for player names when spectating

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua, lua/terrortown/lang/en.lua
=> UI: Grenade Fuse Timer

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
=> Fix Weapon Help Width

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua, lua/terrortown/entities/roles/traitor/shared.lua, lua/terrortown/lang/de.lua, lua/terrortown/lang/en.lua, lua/terrortown/lang/es.lua, lua/terrortown/lang/fr.lua, lua/terrortown/lang/it.lua, lua/terrortown/lang/ja.lua, lua/terrortown/lang/pl.lua, lua/terrortown/lang/pt_br.lua, lua/terrortown/lang/ru.lua, lua/terrortown/lang/sv.lua, lua/terrortown/lang/uk.lua, lua/terrortown/lang/zh_hans.lua, lua/terrortown/lang/zh_tw.lua, lua/terrortown/menus/gamemode/roles/base_roles.lua, lua/ttt2/libraries/roles.lua
also a general rewrite of magneto stick because some parts were really, really strange
=> Magnetostick: Per role ragdoll pinning permissions (fixes #1100)

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua, lua/terrortown/lang/de.lua, lua/terrortown/lang/en.lua, lua/terrortown/lang/es.lua, lua/terrortown/lang/fr.lua, lua/terrortown/lang/it.lua, lua/terrortown/lang/ja.lua, lua/terrortown/lang/pl.lua, lua/terrortown/lang/pt_br.lua, lua/terrortown/lang/ru.lua, lua/terrortown/lang/sv.lua, lua/terrortown/lang/tr.lua, lua/terrortown/lang/uk.lua, lua/terrortown/lang/zh_hans.lua, lua/terrortown/lang/zh_tw.lua, lua/terrortown/menus/gamemode/appearance/crosshair.lua
=> UI: Grenade Throw Arc

CHANGELOG.md, lua/terrortown/entities/items/item_ttt_radar/cl_init.lua, lua/terrortown/lang/en.lua
The builtin radar now shows meters instead of hammer units
=> Radar in Meters

CHANGELOG.md, gamemodes/terrortown/entities/entities/ttt_c4/shared.lua, gamemodes/terrortown/entities/entities/ttt_firegrenade_proj.lua, gamemodes/terrortown/entities/entities/ttt_flame.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua, lua/ttt2/libraries/game_effects.lua
because it looks good instead of bad
=> Moved Fire and Radius Damage to Game Effects Library

gamemodes/terrortown/entities/entities/base_ammo_ttt.lua, gamemodes/terrortown/entities/entities/item_ammo_revolver_ttt.lua, gamemodes/terrortown/entities/entities/ttt_beacon.lua, gamemodes/terrortown/entities/entities/ttt_c4/cl_init.lua, gamemodes/terrortown/entities/entities/ttt_c4/shared.lua, gamemodes/terrortown/entities/entities/ttt_cse_proj.lua, gamemodes/terrortown/entities/entities/ttt_decoy.lua, gamemodes/terrortown/entities/entities/ttt_firegrenade_proj.lua, gamemodes/terrortown/entities/entities/ttt_health_station.lua, gamemodes/terrortown/entities/entities/ttt_radio.lua, gamemodes/terrortown/entities/entities/ttt_smokegrenade_proj.lua
To prevent future issues with inheritance (stack overflow) entities now use DEFINE_BASECLASS as well
=> Entities: Replaced self.BaseClass with BaseClass

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_player_ext.lua
Added sounds to manually weapon pick-up so it is in line with the automatic weapon pick up
https://github.com/TTT-2/TTT2/assets/13639408/84a042e6-529e-452f-a360-346a34fcf617
=> Pickup: Added sounds

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_search.lua
=> Bodysearch: Fixed hook using wrong variable

gamemodes/terrortown/gamemode/client/cl_player_ext.lua, gamemodes/terrortown/gamemode/server/sv_player.lua, gamemodes/terrortown/gamemode/shared/sh_main.lua, gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
The recently added dynamic FOV is really choppy on some servers with high ping or low tickrate. To mitigate this issue, I made everything related to dynamic FOV shared.
=> Predicted FOV changes: Made FOV calls shared

gamemodes/terrortown/entities/entities/ttt_c4/cl_init.lua
it works again [this evil line broke things](https://github.com/TTT-2/TTT2/commit/a52f830afb6b2912d2568c344c923ce0bcfb660d#diff-6f8517483f2d960a76d2a50181ebdda8ae10df6174cdf1713e75c5d5f9636102L189)
=> C4 UI: Fixed C4 UI accessing wrong BaseClass

gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
Nothing major, just something I noticed when working on #1443
=> Placeable Base: Fixed self in table

gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
added the new spring mine to the addon checker
=> Addonchecker: Added spring mine

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_main.lua
Debug preventwin states "prevent any win condition". I think the time limit is a win condition as well but was not prevented with this.
=> Preventwin: Also prevent timelimit

CHANGELOG.md, lua/ttt2/libraries/bodysearch.lua
fixes #1359
https://github.com/TTT-2/TTT2/assets/5711436/2addb0ac-9b65-468b-bb23-04019f592adf
=> detective search results not be overwritten

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_changes.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua
This was 'manually' created with the [ttt2-release_prep](https://github.com/TTT-2/ttt2-release_prep) tool.
=> release: v0.13.2b

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_ttt_flaregun.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_glock.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_sipistol.lua, gamemodes/terrortown/entities/weapons/weapon_zm_pistol.lua, gamemodes/terrortown/entities/weapons/weapon_zm_revolver.lua
changed the holdtype from "pistol" to "revolver"  to better match the 2 hands in the viewmodel
**Before**
**After**
=> Changed holdtype on pistols to better match animations

gamemodes/terrortown/gamemode/client/cl_voice.lua, lua/terrortown/lang/en.lua, lua/terrortown/menus/gamemode/gameplay/sounds.lua, lua/terrortown/menus/gamemode/gameplay/voiceandvolume.lua
Nothing major, I mostly added some documentation and moved some settings around.
=> Settings: Cleaned up voice settings

lua/terrortown/lang/en.lua, lua/terrortown/menus/gamemode/administration/chat.lua
=> Settings: Added docs to server voice settings

gamemodes/terrortown/gamemode/server/sv_addonchecker.lua
added my new mirror fate addon to the addon checker
=> AddonChecker: Added Mirror Fate

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_voice.lua, gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/pure_skin_playerinfo.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttteamindicator/pure_skin_teamindicator.lua
Unified the usage of the new spec color in some places I could find. There are probably more, but that's it for now. Fixes #1481
=> UI: Unified Spec Color

CHANGELOG.md, gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_flaregun.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_stungun.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_teleport.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua, gamemodes/terrortown/entities/weapons/weapon_tttbase.lua, gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua, gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua, gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua
I noticed a few things that could be optimised in the weapon base and grenade base so I applied them 😀 Then I thought I'd check some of the other and went on a bit of a spree of applying minor optimisations to those too (sorry if some seem nitpicky). I can't look through all of them now, not that all of them need optimising, but I feel these are the main ones.
I've tested the weapons after making the changes and they still work.
I also applied a previous fix I made to the weapon base to the binoculars where your view could get stuck zoomed in if your binoculars were removed.
By the way, the reason I removed the lines `gren:SetGravity(0.4)` and `gren:SetFriction(0.2)` from the grenade base's `CreateGrenade` function is because they do nothing to physics entities.
=> Weapons: Minor cleanup and optimizations

gamemodes/terrortown/gamemode/client/cl_targetid.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttpickup/old_ttt_pickup.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttpickup/pure_skin_pickup.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttpunchometer/pure_skin_punchometer.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttwswitch/old_ttt_wswitch.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttwswitch/pure_skin_wswitch.lua
Despite the branch name, this PR unifies more spec colors.
=> Colors: Further Spec Cleanup

gamemodes/terrortown/gamemode/server/sv_corpse.lua
Replaced the body search sounds because they don't exist in Garry's Mod/CS:S/... .
I tried to use other fitting sounds which can be heard here: https://streamable.com/5rijf8
=> replaced missing body search sounds

CHANGELOG.md, gamemodes/terrortown/entities/entities/ttt_c4/cl_init.lua, gamemodes/terrortown/entities/entities/ttt_knife_proj.lua, gamemodes/terrortown/gamemode/client/cl_radio.lua, gamemodes/terrortown/gamemode/client/cl_reroll.lua, gamemodes/terrortown/gamemode/client/cl_transfer.lua, gamemodes/terrortown/gamemode/server/sv_addonchecker.lua, lua/terrortown/entities/items/item_ttt_disguiser.lua, lua/terrortown/entities/items/item_ttt_radar/cl_init.lua, lua/terrortown/menus/gamemode/gameplay/general.lua, lua/ttt2/extensions/table.lua, lua/ttt2/libraries/entity_outputs.lua, lua/ttt2/libraries/gameloop.lua, lua/ttt2/libraries/weaponrenderer.lua
While playing around with the lua language server again i noticed a few things which i have fixed here.
Things marked with `FIXME:` i wasn't exactly sure about and would need some help/input on
=> Various small fixes found through static analysis

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_player_ext.lua, gamemodes/terrortown/gamemode/server/sv_corpse.lua, gamemodes/terrortown/gamemode/server/sv_player.lua, gamemodes/terrortown/gamemode/server/sv_player_ext.lua, gamemodes/terrortown/gamemode/shared/sh_corpse.lua, gamemodes/terrortown/gamemode/shared/sh_entity.lua, lua/ttt2/libraries/bodysearch.lua
This PR fixes multiple issues with corpses
=> Corpse: Improvements and Fixes

lua/terrortown/lang/tr.lua
skip-changelog if possible
Added New Derandomization Lines
Fixed Various Lines
Better Grammer and Context
=> Added New Derandomization Lines

lua/terrortown/lang/ru.lua
Localized all untraslated lines, fixed some old typo
- Changelog is not needed for this PR. There is already a changelog line for a localization stuff from me.
=> Localization: updated Russian localization file

lua/terrortown/lang/tr.lua
Added Button & Lever Lines
skip-changelog if possible
=> Updated Turkish Lines

CHANGELOG.md, lua/terrortown/lang/en.lua, lua/terrortown/menus/gamemode/commands/commands.lua, lua/ttt2/libraries/admin.lua
Added an additional admin command to force a role onto a player.
Tested and worked in v0.14.
See:
=> UI: Added force role admin command

lua/terrortown/lang/tr.lua
=> Updated Turkish Lines (Force Player Role)

CHANGELOG.md, lua/terrortown/lang/ja.lua
Sorry for late.
I updated japanese translation
=> Update Japanse Translation

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_changes.lua, gamemodes/terrortown/gamemode/shared/sh_init.lua
Prepared Release 0.14.0, also cleaned up some things in previous releases
=> Release 0.14.0b

lua/terrortown/lang/fr.lua
misstranslation in role config
=> Fix a huge misstranslation in role config

gamemodes/terrortown/gamemode/client/cl_shop.lua, gamemodes/terrortown/gamemode/shared/sh_shop.lua, lua/ttt2/extensions/draw.lua, lua/ttt2/libraries/bodysearch.lua
Nothing much really, just found some inconsistent doc comments
=> docs: Fix some doc comments

CHANGELOG.md, lua/terrortown/lang/ru.lua
- Localized new string at line 2373.
- Updated the changelog.
=> Russian localization update

lua/terrortown/lang/tr.lua
=> Updated Turkish L10n

gamemodes/terrortown/entities/entities/ttt_game_text.lua, gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/hud_element_base/cl_init.lua, gamemodes/terrortown/gamemode/shared/hud_elements/tttsidebar/old_ttt_sidebar.lua, lua/ttt2/libraries/admin.lua
i've pooled these changes together as all of them are extremely small and all don't warrant a changelog entry imo
=> Various small chores

lua/terrortown/lang/tr.lua
- Added new & missing lines
- Updated some lines to match GMod crowdin translation
- Fixed context a bit
=> Turkish: Update L10n

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_chat.lua
from https://github.com/Facepunch/garrysmod/pull/2229
=> fix players sometimes being revealed as dead when they chat/voicechat right as they die

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_ent_replace.lua
from https://github.com/Facepunch/garrysmod/pull/2139
=> Allow workshop addons to pack rearm scripts

CHANGELOG.md, gamemodes/terrortown/entities/entities/ttt_filter_role.lua
closes https://github.com/TTT-2/TTT2/issues/1786
new ttt_filter_role entity is from https://github.com/Facepunch/garrysmod/pull/2225
=> Support for new TTT entity ttt_filter_role

CHANGELOG.md, gamemodes/terrortown/entities/entities/ttt_c4/shared.lua, gamemodes/terrortown/entities/entities/ttt_radio.lua, gamemodes/terrortown/gamemode/server/sv_entity.lua
from https://github.com/Facepunch/garrysmod/pull/2203
=> Fix C4/Radio sounds not playing outside of PAS

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_gamemsg.lua
from https://github.com/Facepunch/garrysmod/pull/2227
=> Let TTTLastWordsMsg hook override default behaviour

CHANGELOG.md, lua/autorun/gs_crazyphysics.lua, lua/ttt2/libraries/bodysearch.lua, lua/ttt2/libraries/targetid.lua
editing these files will cause errors from trying to use nil upvalues
=> fix lua errors after autorefresh

CHANGELOG.md, gamemodes/terrortown/entities/entities/ttt_health_station.lua, gamemodes/terrortown/gamemode/shared/sh_entity.lua
fixes a bug re-introduced by #1792
=> Fix health station continuous use not working

CHANGELOG.md, gamemodes/terrortown/gamemode/client/cl_keys.lua, gamemodes/terrortown/gamemode/server/sv_player.lua
=> fix prop spec not working

CHANGELOG.md, gamemodes/terrortown/gamemode/server/sv_corpse.lua
This will now add bodygroups to the corpse
=> Corpses: Inherit bodygroups

gamemodes/terrortown/entities/weapons/weapon_ttt_flaregun.lua, gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua
Noticed things could be tidied a bit in these two files
(I don't think this warrants an entry in the changelog)
=> Slight code cleanup in weapon code
