gamemodes/terrortown/gamemode/cl_targetid_main.lua
gamemodes/terrortown/gamemode/init.lua
gamemodes/terrortown/gamemode/player_ext_main.lua

This will fix the default credit system and also adds the "old" mechanic of "the more traitors, the less credits" back.
To alf: Just edit everything to your needs if needed (Maybe a setting to disable the "old" mechanic?), and also ignore the cl_targetid_main..

Fix for default credit system

---

gamemodes/terrortown/gamemode/server/sv_corpse.lua

Fixed bug (well actually just cloning the table..) where fake corpses and sometimes normal corpses would update the Equipments of a Player even if the corpse was already confirmed / created.
Not neccessary to merge, but It's defenetly an advantage for players that know this bug (on my servers they know it and can confirm traitors very very easily).

Fix for fake corpses and rare occasions

---

gamemodes/terrortown/gamemode/client/cl_equip.lua

Old search is not working for some items and thats pretty annoying for some users. Now it really works with the item names a player sees and is used to.

Equip search improvements

---

gamemodes/terrortown/gamemode/server/sv_player_ext.lua

Damagelog depends on this function, other ttt addons might as well. Therefore i thought fixing the problem with damagelogs in the ttt2 project is the better approach.
Also feel free to change my documentation :)

GetAvoidDetective compatibility

---

gamemodes/terrortown/gamemode/shared/sh_main.lua

A really simple change to remove the static player sprint multiplier in favor of a hook. Right now the sprint multiplier ist set with  `ply.sprintMultiplierModifier`, this hook allows to do the same (but stackable) with a hook:
```lua
hook.Add("TTT2PlayerSprintMultiplier", "sprintchange", function(ply, multi)
multi[1] = 10 * multi[1]
end)
```

sprint modifier hook

---

lua/includes/modules/roles.lua
lua/terrortown/entities/roles/ttt_role_base/shared.lua

This is a first approach at cleaning up the ROLE system.
The change is not that big, but should make it more clear for other developers, on how to use the 
`ROLE:PreInitialize()` and `ROLE:Initialize()` functions.  
They are used to clean up the messy hook usage that has since been used to eg. set the `BaseRole` or set the `LANG` entries.
But this mainly addresses the issue with roles that are loaded before other roles, which they reference with their global variables to eg. set the fallback Shop or the `defaultTeam` variable.
Now the loading is ordered in a way, that the global variables of all roles are initialized, then the `ROLE:PreInitialize()` function is called on each role and after setting up the internal default ConVars, etc for each role (see SetupData(v) in the roles module) …

Role loading

---

gamemodes/terrortown/gamemode/server/sv_corpse.lua

Some models have different skins (for example different hair styles, or outfits). By now, the ragdoll will always drop without that skin, which is sometimes annoying for players with customized skins.

Ragdoll Model/Skin "fix"

---

gamemodes/terrortown/gamemode/shared/lang/english.lua

• **Line 274**: it changes the crosshair opacity when not zoomed, while in **line 1148** it changes crosshair opacity when zoomed.
• **Line 1149**: fixed incorrect meaning.
• **Line 1205**: fixed incorrect meaning.
• **Line 1203** & **1206**: this button clears the current bind but not disables it.
Other changes don't need an explanation. =)

Minor changes in the language file

---

.gitignore
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

Rounds fail to start when using [Enhanced Playermodel Selector](https://steamcommunity.com/workshop/filedetails/?id=504945881), as it blocks changes to playermodels and this causes an error. 
This PR adds a ttt_enforce_playermodel ConVar. When set to 0, this disables automatic playermodel-setting at the start of a round, fixing this issue.
I've also added the .idea directory to the .gitignore, for users of IntelliJ IDEA-based IDEs, such as myself. Feel free to cherry-pick out if desired.

ConVar for compatibility with Enhanced Playermodel Selector

---

gamemodes/terrortown/entities/entities/ttt_traitor_button/shared.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
lua/autorun/ttt_bem_autorun.lua
lua/includes/modules/roles.lua

Fixes replicated convars by removing unnecessary FCVAR flags clientside, specifically FCVAR_ARCHIVE.
This is a bug and has been fixed on the dev branch, but for now this is an easy workaround.
This also removes the FCVAR_SERVER_CAN_EXECUTE flag from the bem serverside cvars:
https://github.com/TTT-2/TTT2/blob/9a29e06a5688dcd455cff9ede5375cb0a249edbf/lua/autorun/ttt_bem_autorun.lua#L2-L8
The server could never change them by running a concommand clientside anyways, since replicated convars can only be changed serverside.

Fix replicated convars

---

gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
gamemodes/terrortown/gamemode/client/cl_help.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/shared/lang/english.lua
gamemodes/terrortown/gamemode/shared/lang/german.lua

You no longer have to press secondary attack a second time to stop aiming and instead will stop aiming as soon as you let go of the button. This is disabled by default and can be enabled using the clientside convar ttt2_hold_aim or by checking the checkbox in the gameplay menu. I tried to change as little as possible about how the ironsight actually works in order to keep it compatible with old stuff. I also made sure this doesn't mess with prediction, making this change very stable even at high latency like 300ms. I added some missing functions and fields in order to give people an idea of how they should implement ironsights and zoom and added some missing doc.

Allow hold aim instead of toggle

---

gamemodes/terrortown/gamemode/server/sv_voice.lua

Fixes the bug that your teammates will always show up as if they were talking in teamchat, even when talking in global chat

Fix colleague color bug

---

gamemodes/terrortown/gamemode/client/cl_lang.lua
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/shared/sh_lang.lua

In an attempt to clean up the chaotic language handling in TTT2 addons, I added language file support for addons. After this merge, addons can place their language files in `lua/lang/`.
Example for the jester:
```lua
L = LANG.GetLanguageTable("english")
L[JESTER.name] = "Jester"
L[JESTER.defaultTeam] = "TEAM Jesters"
-- ...
```
The TTT2 language files stay untouched and are loaded on file load. However addon language files are loaded in the `GM:Initialialize` hook to make sure all files are ready and available. The files are included prior to `LANG.Init()`.
I also fixed the docs for `function LANG.GetUnsafeNamed(name)`

added addon language file support

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_eventpopup.lua
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/shared/hud_elements/ttteventpopup/pure_skin_eventpopup.lua
gamemodes/terrortown/gamemode/shared/sh_main.lua

improved the EPOP based on stuff learned while using it
- EPOPs are now always redered, even when dead since they are really good to inform players about upcoming respawns
- even if the system was originally designed to display always only one element, a queue was added since otherwise multiple addons trying to display text might clash
- messages now have a `blocking` flag, if set to false a new message can overwrite the message without waiting in a queue
- also I added a few convenience functions
- improved docs and coding style improvements

improved epop

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_help.lua
gamemodes/terrortown/gamemode/client/cl_hud_manager.lua
gamemodes/terrortown/gamemode/client/cl_network_sync.lua
gamemodes/terrortown/gamemode/client/vgui/cl_hudswitcher.lua
gamemodes/terrortown/gamemode/server/sv_hud_manager.lua
gamemodes/terrortown/gamemode/server/sv_network_sync.lua
gamemodes/terrortown/gamemode/server/sv_player.lua
gamemodes/terrortown/gamemode/server/sv_player_ext.lua
gamemodes/terrortown/gamemode/shared/hud_elements/tttminiscoreboard/pure_skin_miniscoreboard.lua
gamemodes/terrortown/gamemode/shared/sh_network_sync.lua

This removes the unnecessary self reference caused by `TTT2NET:FUNCTIONNAME`.
Another thing we may discuss, is to whether or not rename the module to its lowercase name `ttt2net` but I'm unsure, as this really looks weird. So please let me know what you think!

TTT2NET: Fix naming

---

CHANGELOG.md
lua/terrortown/entities/items/item_ttt_radar/cl_init.lua
lua/terrortown/entities/items/item_ttt_radar/init.lua
lua/terrortown/entities/items/item_ttt_radar/shared.lua

This is a farily small radar rework. These things were changed:
- removed old TTT code
- fixed a rare bug where the radar color had the wrong color
- moved the important radar stuff from client to server (like seriously, why was this on the client in the first place?!)
- added the possibility to give radar points a custom color
- added a convenience function for the creation of radar points: `RADAR.CreateNewTarget(ply, pos, ent, color)`
- added the possibility to change the radar time by either setting `ROLE.radarTime` or calling `RADAR.SetRadarTime(ply, time)`

Radar Rework

---

lua/ttt2/libraries/door.lua

fixed double door grouping (#542). Previously I falsely simplified it to only group doors that don't have the same default rotation. Now only doors with inverted default rotation are grouped.

fixed door grouping

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_scoring.lua

This implements the changes made by Kefta in https://github.com/Facepunch/garrysmod/pull/1677
The code is adjusted at some points to work with TTT2 and is not exactly the same.
Thank you @Kefta for letting us use this code and your contribution!
As a reference, this is the original commit message from Keftas commit:
- The CLSCORE panel now adjusts its width to the win text, fixing clipping with some languages (https://github.com/Facepunch/garrysmod/pull/1672). This required moving the win calculations to ``CLSCORE:ShowPanel`` from ``CLSCORE:BuildHilitePanel``
- ``CLSCORE:BuildHilitePanel(Panel base)`` -> ``CLSCORE:BuildHilitePanel(Panel base, WinTitle /*See definition at the bottom*/ title, Number starttime, Number endtime)``
- Changed Error calls to error as Error is no longer halting …

Adjust CLSCORE to fix clipping title

---

gamemodes/terrortown/gamemode/server/sv_armor.lua

Adds the option to toggle wether or not blast damage should be considered by the armor system. Reason: Jihad bombs for example cannot kill a player anymore when the advanced armor system is in place because the damage gets below 100.

Blast damage handling

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_scoring.lua
gamemodes/terrortown/gamemode/server/sv_scoring.lua

This PR roughly adopts https://github.com/Facepunch/garrysmod/pull/1678
but uses the stream functions of TTT2 instead.
It moves the old custom implemented event stream to our new net.SendStream and net.ReceiveStream methods and removes now unused code / comments.
This also adjusts the events to store their exact date and other values, according to the PR linked above, as they can also now be sent without any problems (even though we are not relying on the Json function and are using pON instead).

Adjust CLSCORE to use the new stream net functions

---

gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/client/cl_targetid.lua
gamemodes/terrortown/gamemode/server/sv_corpse.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/shared/sh_include.lua
gamemodes/terrortown/gamemode/shared/sh_replicated_cvar.lua

moved replicated cvars into seperate file to prevent them from being created all over the place

Fix confirmation cvars

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/sh_door.lua

fixed problems with area portals on dedicated servers by adding a zero seconds timer.

Doors: Move destruction to next frame to avoid "area portals"

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_target_data.lua
gamemodes/terrortown/gamemode/client/cl_targetid.lua

Added two hooks to modify the targetID base data.
`GM:TTTModifyTargetedEntity(ent, distance)`: Modify the entity that is targeted. This is useful for addons like an "Identity Disguiser".

TargetID: Added hooks for modification

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/hud_elements/tttdnascanner/pure_skin_dnascanner.lua

The hudelement isn't visible for spectators anymore, which removes inconsistencies with the network syncing when spectating a player, who holds a DNA scanner
Addresses possibly the bug mentioned in #569

DNA Scanner HUDElement Fix

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_keys.lua
gamemodes/terrortown/gamemode/client/cl_lang.lua
gamemodes/terrortown/gamemode/client/cl_targetid.lua
gamemodes/terrortown/gamemode/shared/lang/english.lua
gamemodes/terrortown/gamemode/shared/lang/german.lua
gamemodes/terrortown/gamemode/shared/lang/italian.lua
gamemodes/terrortown/gamemode/shared/lang/polish.lua
gamemodes/terrortown/gamemode/shared/lang/russian.lua
gamemodes/terrortown/gamemode/shared/sh_weaponry.lua
lua/terrortown/entities/items/item_ttt_disguiser.lua

Cleaned up the disguiser code and moved the icon to the status system. This way it is only displayed while the player is disguised to remove the redudancy with the text displayed ob top of the HUD.

Disguiser: Rework

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/shared/sh_item_module.lua
lua/includes/modules/items.lua

In this change, the function to initialize legacy items is now properly contained inside the items module and is called directly in the respective InitPostEntity functions on the client / server, instead of using the hook. 
This also removes the timer delay for migration messages, as there should not be any difference. 
Closes #547

ITEMS: Moved legacy item initialization to items module

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_roleselection.lua

This leads to extremely bad RNG as the first numbers generated from
seed values that are close together are not random enough. This leads to
similar or identical role selection, especially for low player counts.
More details in this write up:
https://gist.github.com/JustHev/42c5fc970bb75ddb17e8128a5c29ef98

Roleselection: Do not reseed the RNG just before role selection

---

gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua

This replaces the `self.Owner` calls with the recommended `GetOwner()` function.

Deprecation: Fix not using GetOwner()

---

gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/shared/sh_init.lua
gamemodes/terrortown/gamemode/shared/sh_main.lua

This removes the random reseeding every round and also moves the buytable resets to their appropriate functions.
Also this moves the hooks with their documentation to the correct sh_main file, as they are shared.

Cleanup: Move round state hooks & remove hook add

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

If the model is changed while already having a different hand-model, the hand-model will not update. This will fix that issue.

HandModels: fixed hand models not updating correctly

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/sh_sprint.lua

The current sprint system allows players to sprint continuously by jumping to regain stamina.
This PR aims to fix this "issue"
Players have to be on ground to be able to sprint and players can't replenish their stamina when they're airborne.

Sprint: airborne players can no longer replenish stamina

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_hud_manager.lua

This fixes saving the values to the database, where the path was just wrong.
This fixes #610 and was tested by me.

HUDManager: Fix saving forcedHUD and defaultHUD values to DB

---

CHANGELOG.md
lua/terrortown/entities/items/item_ttt_radar/cl_init.lua

This will ensure that TTT items, which do not know about the new team property, will still be displayed.

Radar: Make bomb.team optional to fix compatibility

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player.lua

This removes the timer in sv_player, that would delay handling the death to the next frame, as this leads to multiple corpses etc, when a player dies from damage and a `ply:Kill` command in the same frame.
Don't know why this timer even was introduced, maybe @Alf21 knows something about this?
Fixes #611

Corpses: Fix multiple corpses

---

gamemodes/terrortown/gamemode/server/sv_addonchecker.lua

The Golden Deagle V1, V2 and the Juggernaut Suit were updated by Zaratusa. They are now compatible with TTT2 and can be removed from the Addonchecker.

Update sv_addonchecker.lua: Removed updated and now compatible Addons

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_targetid.lua

Innocents are not considered special, so no role icons were shown to
innocents, although Detective Icons should be shown to them.

Overhead Icons: Changed detective overhead icon to show to innocents

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player.lua

If you crouch to stop spectating a player and want to slowly move while free-roaming and hold duck, you are teleported back to the person you were previously spectating. There is no need for this since if you want to return to the person you were spectating, you can just use your reload bind.
Change regarding https://github.com/Facepunch/garrysmod/pull/1696

Spectators: Stop teleporting players to players they're not spectating

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/shared/sh_init.lua
gamemodes/terrortown/gamemode/shared/sh_lang.lua
lua/ttt2/libraries/fileloader.lua

This new file loader is heavily based on the old language file loader but is now more widely used.
CHANGED:
Language files are moved from `lua/lang/` to `lua/terrortown/lang/`. However the old path is loaded as well for now with a deprecation warning.
ADDED:
Added a new fileloader for addon files that were previously placed inside of `lua/autorun/` and were loaded in all gamemodes. This caused problems for players that switched between gamemodes. Additionally files inside those new folders are loaded directly after all TTT2 gamemode files are loaded. This has the added benefit that right from the time the files are loaded, all gamemode functions and library extensions are available.
The new path for files is `lua/terrortown/autorun` with three seperate subfolders for `client`, `server` …

Fileloader: Introduced a new file loader to TTT2

---

.github/workflows/ci.yml
gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua

This adds a CI workflow using Github Actions for the glualint tool.
The Jenkins build will then no longer be needed and all checks / output is available right here on Github, while also reducing the needed maintenance.

CI: Move glualint workflow to github action

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/huds/base_huds/hud_base/cl_init.lua

This patch fixes the `savingKeys` table to be unique and not accidentally shared across all HUD's so that for example the old HUD does not falsely receive a base color attribute.

HUD: Fix saving keys table to be unique for each HUD

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/lang/spanish.lua

-Added a translation for the 2020-08-07 and 2020-08-11 text lines.
-Fixed a word missplacement in the death confirmation notification, showing the word "Era" twice (in english being like "They were were a Traitor!").
-Changed a duplicated translation for the detectives only inspect and confirm corpse game mechanic, being almost the same, so now you can tell the difference which one is enabled.
-Improved typing and grammar where needed for "better a sounding" translation.

Language: Spanish translation update

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_targetid.lua

fixes the shown bug where the `+use` key was displayed even though pickup has its own keybind

TargetID: Fix weapon key info

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
gamemodes/terrortown/gamemode/shared/sh_init.lua

Added a team indicator in front of every name in the scoreboard. I thought about a role indicator (instead of / as well), but came to this solution (a discussion is always welcome).

Scoreboard: Team indicator

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_corpse.lua
lua/terrortown/entities/items/item_ttt_radar/cl_init.lua

This is a really small change that adds a serverside hook that is called once a player pressed the "call detective" button. This was requested by @blackmagicfine on discord.
Additionally I changed `LANG.Msg` to `LANG.MsgAll`. The previous usage of the function already resulted in a message to everybody, however it isn't obvious to someone new and therefore bad coding style.
Please don't merge this until it is tested. While it doesn't throw errors and looks good to me, the functionality has to be confirmed.

Call Detective Hook: added serverside hook on "call detective"

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua

This should fix the crash while providing an error that should help to fix further connected problems.

DNA Scanner Crash: Added a check to prevent crash if using an old weapon base

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/sh_speed.lua

This patch avoids the invalid nil state of the oldval variable in case the users speedMultiplier is not 1 at the initialization.
This is now fixed, by using the GetSpeedMultiplier method, which returns either the speedModifier or 1.0

Speed: Fix initialization of oldval

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player_ext.lua

Fixed bug where some weapons would stay in inventory even though they should get dropped, leading to a player being able to pickup pretty much infinite weapons. (Yes I know its just a timer)

Weapon Pickup: Fixed pickup bug

---

gamemodes/terrortown/gamemode/client/cl_targetid.lua

While renaming variables in a previous PR, a material path was affected as well. This resulted in the checkerboard pattern of overheadicons

Overhead Icon: Fixed material name

---

gamemodes/terrortown/gamemode/shared/sh_include.lua

`cl_fonts.lua` doesn't exist anymore and should not be included

removed inclusion of non-existant file

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_addonchecker.lua

Removed the addons mentioned in #696 as they are now using the ttt2 sidebar.
(I also capitalized some entries in the Changelog)

Addonchecker: Removed some updated addons

---

lua/ttt2/extensions/util.lua

Fixed a library cache variable to point to the correct library instead of `nil`

[FIX, util] Fixed library cache name

---

gamemodes/terrortown/gamemode/client/cl_lang.lua

This patch fixes the variable name cached_active to the now renamed cachedActive.

Lang: Fix variable name in SetActiveLanguage method

---

gamemodes/terrortown/gamemode/client/cl_help/populate_language.lua
gamemodes/terrortown/gamemode/client/cl_lang.lua
gamemodes/terrortown/gamemode/client/cl_radio.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua
gamemodes/terrortown/gamemode/shared/lang/chef.lua
gamemodes/terrortown/gamemode/shared/sh_lang.lua

Prevent the language menu from rebuilding indefinitely. fixes #705

LANG: Fix indefinitely rebuilding language settings menu

---

.github/workflows/ci.yml
gamemodes/terrortown/gamemode/client/cl_lang.lua

This bumps the NeoDoc version to the newest, which can provide annotations with its errors to pull requests.
This is how it would look like in a PR "Files changed" view:

CI: NeoDoc bump to v0.1.4

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_karma.lua
gamemodes/terrortown/gamemode/server/sv_player.lua

Fixed so karma will no longer be accounted for in the damage if the system was disabled.
Related to https://github.com/TTT-2/TTT2/issues/686

Karma: Fixed karma damage bug

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_roleselection.lua

Before this fix, there was a for-loop that should have been repeated with the same index, if certain conditions were met. As lua creates a fixed set of indizes, which it internally iterates through changes to the index i in this case had no effect. Therefore if an empty layer was found, the next layer got also skipped as a consequence.
The Fix therefore now safely iterates through the layers until a valid layer is found and chooses a role out of it.
In case it still has baseroles left, but doesnt find a valid layer, the rest of available base roles are chosen after that. That's why I switched from if-else to two if-statements.
Still missing is a fix to the subroles, which are a bit more tricky. But this is my first draft for discussion.

Roleselection: Fix Layering

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua

Fixed Magneto Stick ragdoll pinning instructions not showing for innocents when ttt_ragdoll_pinning_innocents is enabled

Weapon - Magnetostick: Fix inno ragdoll pinning

---

CHANGELOG.md
lua/ttt2/libraries/classbuilder.lua
lua/ttt2/libraries/events.lua
lua/ttt2/libraries/targetid.lua

Right now inheriting on the same base from different calls does not work because the base is restricted to the one call for one specific folder. I change it in such a way that a table can be passed through.
Additionally I improved the event loading print.

Classbuilder: Fixed inheriting from same base

---

CHANGELOG.md
lua/ttt2/libraries/vskin.lua

Fixed the module name for the `vskin` module.

Docs: Module name fix

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_transfer.lua
gamemodes/terrortown/gamemode/server/sv_shop.lua

The TTT2CanTransferCredits hook from my previous pull request seems to have messed with the API Documentation somewhat:
Based on the layout, it seems like it should be a part of the GM section, so I went ahead and made that change. Not sure why the right panel has "()" and nothing else.

Credits: Made TTT2CanTransferCredits a part of GM

---

CHANGELOG.md
lua/ttt2/extensions/util.lua

This small patch just adds an alias for the util function IsOffScreen() as a global function, cause this breaks tttdamagelogs for example.

Compat: Add global alias for util.IsOffScreen

---

CHANGELOG.md
lua/ttt2/libraries/outline.lua

This will fix #736 and therefore makes the outline library finally work as intended.
By inputting the client as self into the function call, we now really get if the line of sight is clear.
Before that, the call broke as it didnt get enough arguments.
Also explaining why it didn't occur before with addons like glowing teammates and probably the glowing jester:
Global variables of modules created with module("name",package.seeall) need to be accessed via their modulename:
So outline.OUTLINE_MODE_NOTVISIBLE instead of just the variablename.
This might lead to addons not working as intended anymore. They should evaluate if they might need the OUTLINE_MODE_NOTVISIBLE mode instead now, so that teammates are visible only through walls or the other way round with OUTLINE_MODE_VISIBLE only if …

Fixed outline library

---

.github/workflows/ci.yml

This should fix the `./glualint: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory` error in CI.
ref: https://github.com/FPtje/GLuaFixer/releases/tag/1.17.2

CI: fix CI by bumping glualint to v1.17.2

---

CHANGELOG.md
lua/ttt2/extensions/util.lua

This fixes a mistake, where the `util.IsOffScreen` function is being exposed as a global function, before it is defined.
PR, that introduced the mistake: https://github.com/TTT-2/TTT2/pull/731

Util: Fixed IsOffScreen function being global for compatibility

---

gamemodes/terrortown/gamemode/shared/events/c4explode.lua
gamemodes/terrortown/gamemode/shared/events/c4plant.lua

Removed .owner as the Event doesn't have an owner sub table. Alternatively, could change the self:Add() to add the parameters in an owner table.

Fixed c4 plant event references for GetText()

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/sh_main.lua

#810
Instead of limiting to the players max speed, which doesnt change while crouching, we now check for the real speed, which is 60 for crouching, 100 for slowwalking and 220 for normal walking. Everything below 150 is now muted.
If someone can bhop and is faster than 150 you can hear him. Therefore cant be abused anymore.

Footsteps: Fixed silenced footsteps when moving fast while crouching

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_chat.lua
gamemodes/terrortown/gamemode/server/sv_gamemsg.lua

This pull request fixes two issues:
- Fixed issue where base innocents could bypass the TTT2AvoidGeneralChat and TTT2AvoidTeamChat hooks with the team chat key.
- Fixed issue where roles with unknownTeam could see messages sent with the team chat key
Explicitly, checks for determining whether a player can use/read team chat messages involved the "IsSpecial" function, which only checks if the player is a non-innocent (and further lead to strange behavior with the team chat key). I altered the functionality to be more like voice chat: unknownTeam is used instead now. If the player is on an unknownTeam (Innocents, Detectives, Amnesiacs, etc.), they can technically open up the text box to type messages with the team chat key, but no message will be displayed or sent.

TeamChat: Fixed issue where base innocents could bypass chat hooks

---

gamemodes/terrortown/gamemode/shared/events/kill.lua
gamemodes/terrortown/gamemode/shared/lang/de.lua
gamemodes/terrortown/gamemode/shared/lang/en.lua
gamemodes/terrortown/gamemode/shared/lang/es.lua
gamemodes/terrortown/gamemode/shared/lang/fr.lua
gamemodes/terrortown/gamemode/shared/lang/it.lua
gamemodes/terrortown/gamemode/shared/lang/ja.lua
gamemodes/terrortown/gamemode/shared/lang/pl.lua
gamemodes/terrortown/gamemode/shared/lang/ru.lua
gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua

In the current version the game tries to display the killer information even if it is unknown. I therefore removed it. I *think* the `_using` flag to the strings is only set if a player was the killer and the info is therefore available. This is at least what I'd say after looking at the text generating code (which is from original TTT) and I confirmed it with bot tests.
In the screenshot you see the problem before the fix:

Round End Screen: Fixing killer role/team for "something"

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
gamemodes/terrortown/gamemode/shared/lang/de.lua
gamemodes/terrortown/gamemode/shared/lang/en.lua
gamemodes/terrortown/gamemode/shared/lang/es.lua
gamemodes/terrortown/gamemode/shared/lang/fr.lua
gamemodes/terrortown/gamemode/shared/lang/it.lua
gamemodes/terrortown/gamemode/shared/lang/ja.lua
gamemodes/terrortown/gamemode/shared/lang/pl.lua
gamemodes/terrortown/gamemode/shared/lang/ru.lua
gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua

Added per-player volume control by hovering over the mute icon and scrolling up/down.
Demonstration again: https://cloud.nickcloud.at/index.php/s/XELpDHGTLZfXJBf

Scoreboard: Added per-player volume control

---

CHANGELOG.md
lua/terrortown/menus/gamemode/legacy.lua
lua/terrortown/menus/gamemode/legacy/base_legacy.lua

As the panel always gets deleted, when it's parent gets deleted, we have to recreate it everytime we fetch a submenu.
This is a dirty workaround to get the job done. Better would be to free the child of its parent before clearing it. This also calls the hook  `TTTSettingsTabs` again everytime we open another legacy addon submenu.

F1 Menu: Legacy Addons: Fix Null Panel

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_transfer.lua
gamemodes/terrortown/gamemode/shared/lang/de.lua
gamemodes/terrortown/gamemode/shared/lang/en.lua
gamemodes/terrortown/gamemode/shared/lang/es.lua
gamemodes/terrortown/gamemode/shared/lang/fr.lua
gamemodes/terrortown/gamemode/shared/lang/it.lua
gamemodes/terrortown/gamemode/shared/lang/ja.lua
gamemodes/terrortown/gamemode/shared/lang/pl.lua
gamemodes/terrortown/gamemode/shared/lang/ru.lua
gamemodes/terrortown/gamemode/shared/lang/zh_hans.lua

This patch will list teammates first in the credit transfer menu and prepend a "(Team)" string behind their names to make them easily distinguishable for sending out credits to people that are important.
This fixes #734

Credit transfer: Sort teammates first and show indicator

---

CHANGELOG.md
lua/ttt2/extensions/table.lua
lua/ttt2/libraries/classbuilder.lua

This bug was unnoticable before todays rework in #823 because we never inherited more than two layers deep which worked because the files were in different folders. Therefore this bug was only noticed this late. Now inheritance works on infinitely deep layers.
Additionally I had to add this modification to the `table.DeepInherit` function to prevent the function to add a baseclass to every empty table. I'm not 100% sure why I had to do this now, but I guess it makes sense.

Classbuilder: added recursion

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/hud_elements/base_elements/pure_skin_element.lua

I noticed, that the text positioning in a pure_skin bar is not really consistent at different screen resolutions.
This has caused problems especially with a new HUD element, but it is also noticeable in the player info panel. 
I have tested this at various screen resolutions between 720p and 3000x2000, and it seems to be positioned consistently with the proposed change. 
It also looks good with the Vampire and Bodyguard role. But I have not tested more than that.
This is at 1080p and 2560x1600.

pure_skin: consistent text positioning in pure_skin bar

---

gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua

Editing distance is now as far as visuals go.
Highlighting/Selecting spawn is now scaled to sphereRadius, fov and resolution.
Theoretically an angle between view-direction and (spawnPos - eyePos) needs to be calculated to have correct 3D-Visuals of a sphere when highlighting. If you go really close to the sphere the used distance is wrong and the it doesnt detect when you point to the outer ring of the sphere. For normal and far distances this value is okay.

Weapon Spawn Rework: Change edit distance and scale highlighting

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/client/cl_network_sync.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/server/sv_network_sync.lua
gamemodes/terrortown/gamemode/shared/hud_elements/tttminiscoreboard/pure_skin_miniscoreboard.lua
gamemodes/terrortown/gamemode/shared/sh_main.lua
gamemodes/terrortown/gamemode/shared/sh_network_sync.lua
lua/ttt2/libraries/bind.lua

Fixed hotreloading for
- TTT2NET
- HUDs
- Bindings
Based on [this article](https://wiki.facepunch.com/gmod/Auto_Refresh) I reworked the way data is stored. This way (I verified this) data is persistent over hot reloading. For HUDs I decided against this approach because in my opinion HUDs should refresh on reload so the user sees their change (i.e. the language system blocks data reloading which is annoying imo). Therefore I added a simple reload in `GM:OnReloaded`.
Additionally I cleaned up the bindings library a bit.

Hot-Reloading: Fixed data persistency on hotreload

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player.lua
lua/terrortown/lang/de.lua
lua/terrortown/lang/en.lua
lua/terrortown/lang/es.lua
lua/terrortown/lang/fr.lua
lua/terrortown/lang/it.lua
lua/terrortown/lang/ja.lua
lua/terrortown/lang/pl.lua
lua/terrortown/lang/ru.lua
lua/terrortown/lang/zh_hans.lua
lua/terrortown/lang/zh_tw.lua

This code change was made for reviving roles such as Pharaoh, Occultist, and Cursed. Each of these roles are likely to revive after death, but not immediately. During that 10 or so seconds they can browse the roles of other players, which they shouldn't know since they're about to re-enter play.
So this change prevents that. While the revive timer is going, the spectator can move around, but can no longer enter first-person view of an alive player to see their role, or look at unidentified corpses.

Revive: Prevent spectators about to revive from gathering player info

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
gamemodes/terrortown/gamemode/client/cl_equip.lua
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/shared/sh_equip_items.lua
gamemodes/terrortown/gamemode/shared/sh_init.lua
gamemodes/terrortown/gamemode/shared/sh_main.lua

This fixes the hotreloading problems with ttt2 missing certain key-values like .id or ttt2_cached_material.
It also cleans up the old code and reduces number of loops for weapons.GetList().
As a bonus I added the possibility to add HotReloadableKeys as a list of strings to make data saved via weapons.GetStored() inside the original SWEP-files to be persistent across hotreloads, if you need some variables to keep on counting.
As this was a deep going fix, I'd appreciate some tests and am open for critics as it might be that I dont see clear on this matter anymore 😄 To see how the weapons get registered and the hook "PreRegisterSWEP" gets ran look into garrysmod files directly under \garrysmod\lua\includes\modules\weapons.lua

Hotreload: Weapon hotreloading fix and persistent data across reloads

---

gamemodes/terrortown/gamemode/shared/sh_main.lua
materials/vgui/ttt/tid/tid_big_ammo_deagle.vmt
materials/vgui/ttt/tid/tid_big_ammo_mac10.vmt
materials/vgui/ttt/tid/tid_big_ammo_pistol.vmt
materials/vgui/ttt/tid/tid_big_ammo_random.vmt
materials/vgui/ttt/tid/tid_big_ammo_rifle.vmt
materials/vgui/ttt/tid/tid_big_ammo_shotgun.vmt
materials/vgui/ttt/tid/tid_big_player.vmt
materials/vgui/ttt/tid/tid_big_weapon_assault.vmt
materials/vgui/ttt/tid/tid_big_weapon_melee.vmt
materials/vgui/ttt/tid/tid_big_weapon_nade.vmt
materials/vgui/ttt/tid/tid_big_weapon_pistol.vmt
materials/vgui/ttt/tid/tid_big_weapon_random.vmt
materials/vgui/ttt/tid/tid_big_weapon_shotgun.vmt
materials/vgui/ttt/tid/tid_big_weapon_sniper.vmt
materials/vgui/ttt/tid/tid_big_weapon_special.vmt

Apparently materials drawn in WEAPON:RenderScreen need an additional $ignorez parameter to be properly drawn
https://wiki.facepunch.com/gmod/WEAPON:RenderScreen
https://developer.valvesoftware.com/wiki/$ignorez
A GIF to show all icons.
https://gyazo.com/c6232577957bc84fc910179d88bf59a1
Also fixed a little hotreloading bug, when no keys are defined.
Not gonna merge it directly, so you can see the changes.

Weapon spawn rework breaker

---

gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua
gamemodes/terrortown/gamemode/shared/sh_main.lua
materials/vgui/ttt/tid/tid_big_ammo_deagle.vmt
materials/vgui/ttt/tid/tid_big_ammo_mac10.vmt
materials/vgui/ttt/tid/tid_big_ammo_pistol.vmt
materials/vgui/ttt/tid/tid_big_ammo_random.vmt
materials/vgui/ttt/tid/tid_big_ammo_rifle.vmt
materials/vgui/ttt/tid/tid_big_ammo_shotgun.vmt
materials/vgui/ttt/tid/tid_big_player.vmt
materials/vgui/ttt/tid/tid_big_weapon_assault.vmt
materials/vgui/ttt/tid/tid_big_weapon_melee.vmt
materials/vgui/ttt/tid/tid_big_weapon_nade.vmt
materials/vgui/ttt/tid/tid_big_weapon_pistol.vmt
materials/vgui/ttt/tid/tid_big_weapon_random.vmt
materials/vgui/ttt/tid/tid_big_weapon_shotgun.vmt
materials/vgui/ttt/tid/tid_big_weapon_sniper.vmt
materials/vgui/ttt/tid/tid_big_weapon_special.vmt

Apparently outside of render Hooks the global EyeAngles() is unreliable. It worked on Tim's Pc but not on mine. Don't really know why.
https://wiki.facepunch.com/gmod/Global.EyeAngles
Also let the traces start a bit outside of the walls to be safe not to hit the same spot again.

Weapons: Weapon spawn rework Fix 3D-Positioning

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

Changed the "IsSpecial" or "HasSpecialRole" function to also return "false" if the player has "ROLE_NONE".
This also fixes an issue with the Clairvoyant role.

Role function: Changed HasSpecialRole

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_chat.lua
gamemodes/terrortown/gamemode/server/sv_corpse.lua
gamemodes/terrortown/gamemode/server/sv_gamemsg.lua
gamemodes/terrortown/gamemode/server/sv_networking.lua
gamemodes/terrortown/gamemode/server/sv_weaponry.lua
lua/terrortown/entities/roles/ttt_role_base/shared.lua

- all public policing roles now appear as detectives in the chat
- fixed that every policing player could be called to a corpse, this is now again restricted to alive only players
- added the hook `GM:TTT2CalledPolicingRole` that is called after all policing role players were called to a corpse
- fixed inconsistency between `.disabledTeamChatRecv` and `.disabledTeamChatRec`
- fixed non-public policing roles having hats and therefore confirming them
- small cole and docs cleanup

Role Enhancement: Called Policing Role Hook and Added Docs

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_player_ext.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/server/sv_player_ext.lua
gamemodes/terrortown/gamemode/shared/sh_init.lua
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

Change blocking revival mode from `true`/`false` to
- `REVIVAL_BLOCK_NONE`: don't block the winning condition during the revival process [default, previously `nil`/`false`]
- `REVIVAL_BLOCK_COUNT_AS_ALIVE`: only block the winning condition, if the player being alive would change the outcome [previously `true`]
- `REVIVAL_BLOCK_UNTIL_ALIVE`: block the winning condition until the revival process is ended
- the old arguments still work, they are automaticvally converted

Revival: Add Block Modes

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_random_ammo.lua
gamemodes/terrortown/entities/entities/ttt_random_weapon.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
lua/ttt2/libraries/entspawn.lua

Maps like
- Kakariko https://steamcommunity.com/sharedfiles/filedetails/?id=118937144
- Mc Jondome https://steamcommunity.com/sharedfiles/filedetails/?id=322655757
have spawns through an env_entity_maker https://developer.valvesoftware.com/wiki/Env_entity_maker, which disables the random spawns entity on map initialization and only activates them when a trigger is activated. 
On Kakariko its destroying the vases, on jondome the using of chests.
As we delete all random spawn entities on mapcleanup and make a manual call to spawn, we removed the spawning of weapons inside the initialization, which made those maps not working correctly.
Now we set a boolean after the cleanup and allow those later appearing instances to spawn weapons again, but still going over spawn type system.

Weapon Spawn: Fix late random weapon spawns on maps like kakariko

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_roleselection.lua

This patch potentially corrects the filtering of available baseroles.
When the system goes through all layers for each baserole it does not consider the amount of players that can take the role and thus how many players can already be assigned to a role.
With the new condition it will now correctly stop adding baseroles to the final baserole selection table (marked as available), if the amount is equal to the player amount. This ensures that layering actually influences the availability of base roles and thus won't lead to weird issues further down.
The final role assignment also implicitly assumes that the actual selection of what roles appear is already made in the filtering of available roles. This should now work as intended.
This patch still needs testing and verification.

Roleselection: Fix available baseroles calculation by considering maxPlys when filtering

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
lua/ttt2/libraries/items.lua

This patch moves the initialization code specific to items into the items.OnLoaded() function and adds the call to the function to the OnReloaded hook as we do with all other things like huds etc.
This needs discussion, since im not particularly happy about such gamemode stuff / dependencies on those functions inside the items module. But on the other hand it really is a function that is tied to the gamemode.
Another idea would be to only move the ITEM:Initialize call to the items.OnLoaded() function and not touching the ShopEditor related initializations at all.

Items: Fix hotreload

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_main.lua

Currently the random playermodel selection on round change is broken. Moving the random selection until after the initialization fixes this.

Playermodels: Fixed Random Selection on Map Change

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player_ext.lua
gamemodes/terrortown/gamemode/server/sv_weaponry.lua

This PR fixes #861 by moving the weapon teleportation code into a conditional check. It also removes the timer around the weapon drop. After some testing I came to the realization that the timer doesn't seem to make a difference. However it causes problems when switching between two weapons with the same class, because then the pickup fails since the weapon is dropped a tick later.
The solution here was to either add a single tick timer to the pickup function as well, or to remove the existing drop timer. I chose the latter here.

Weapon Pickup: Fixed Flying Weapons

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_targetid.lua

This patch adjusts the color of overhead icons to match the info box role icon. It will now select white / black depending on the role's color.

Overheadicons: Color icon based on role color

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/vgui/cl_sb_main.lua
gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/old_ttt_info.lua
gamemodes/terrortown/gamemode/shared/hud_elements/tttroundinfo/pure_skin_roundinfo.lua
lua/terrortown/entities/roles/traitor/shared.lua
lua/terrortown/entities/roles/ttt_role_base/shared.lua

This new role variable moves yet another traitor feature to the role base. If `isOmniscientRole` is set to true, the role is able to see the haste mode timer as well as missing in action players.

Role Agnostics: IsOmniscientRole

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_targetid.lua

Added a hook to add, remove or modify the overhead icon:
```lua
---
-- Can be used to modify, disable or add an overhead icon of a player.
-- @param Player ply The player whose overhead icon should be modified
-- @param boolean shouldDrawDefault Defines if the overhead icon would draw normally
-- @return boolean Return false to prevent overhead icon draw
-- @return Material The material for the overhead icon (normally the role icon)
-- @return Color The color of the overhead icon backdrop
-- @hook
-- @realm client
function GM:TTT2ModifyOverheadIcon(ply, shouldDrawDefault)
end
```
Example usage in the identity desiguiser:
```lua
hook.Add("TTT2ModifyOverheadIcon", "ModifyDisguiserOHI", function(ply, shouldDrawDefault)
if not ply:IsPlayer() or not ply:HasDisguiserTarget() then return end …
```

Overhead Icon: Made modifyable

---

gamemodes/terrortown/gamemode/client/cl_lang.lua

This code is no longer used and caused an error because a local variable got removed.

Fix: Removed Unused Code

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player_ext.lua

We removed a flag, that was used for cached weapons. As the spawneditor is given after caching, we need the forcedGive flag.

Spawneditor: Fixed giving spawneditor when weapons are cached

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua

It took some time, but after glitching through some walls it happened and I can confirm the error of #904 
I also then forced it to happen and that at least confirms my suspicion that drawSphere cant handle infinity.
```
previewData.distance3d = math.floor(previewData.distance3d)
if previewData.distance3d <= 0 then
print(previewData.distance3d)
end
```
So this fix should handle that special case and also handle some framedrops, when being close to spheres. As this is an admin tool, I guess we dont need it to be super high fidelity. 🤔 
Opinions on only 10 steps shown in the picture on 2k resolution?

Spawneditor: Fix too many steps (leading up to infinity)

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_karma.lua
lua/terrortown/entities/roles/ttt_role_base/shared.lua

This is a very basic karma var system that could be extended in the future. We opted for this very simple approach, because it can always be extended at a later point. But a more in-depth system would need a whole system rework first.
The following vars have been added:
- `ROLE.karma.teamKillPenaltyMultiplier`: The multiplier that is used to calculate the Karma penalty for a team kill
- `ROLE.karma.teamHurtPenatlyMultiplier`: The multiplier that is used to calculate the Karma penalty for team damage
- `ROLE.karma.enemyKillBonusMultiplier`: The multiplier that is used to change the Karma given to the killer if a player from an enemy team is killed
- `ROLE.karma.enemyHurtBonusMultiplier`: The multiplier that is used to change the Karma given to the attacker if a player from an enemy team is …

Karma: Added Multiplicators

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player.lua

As the amount of damage cant be changed in the hook, we use now the info from dmginfo:GetDamage() instead and therefore take everything that is scaled due to hooks and armor and Karma into account.
Warning: This is untested, but should work in theory!

Damage Overlay: Fix unscaled damage being shown

---

CHANGELOG.md
lua/terrortown/entities/roles/ttt_role_base/shared.lua

In a recent code refactoring I accidentally set the default of the traitor button variable to 1. I reset that to 0. This caused the reports that for new people innocents could access traitor buttons.

Roles: Initial Traitor Button

---

CHANGELOG.md
lua/ttt2/extensions/cvars.lua

First doing this as a draft, as there are some more mistakes I found while copying the code to my new module. Trying to remember them now, but this here could fix a theoretical error of locally cached/stored variables not being affected by serverside changes as they are not correctly addressed.

ConVars: Fix theoretical indexing error at 0

---

CHANGELOG.md
lua/terrortown/menus/gamemode/equipment.lua
lua/terrortown/menus/gamemode/equipment/base_equipment.lua

To have the inherited versions for the AddToSettingsMenu-function, we used the weapons.Get-function which cached an inherited copy of the original weapons table. But as synchronization only affects the original table not the copied cached one, we need to get it as late as possible.
I know that at this point we could also just check if the function is given, but I would rather have the option available to later patch in a default AddToSettingsMenu directly in the ttt_weaponbase.

Equipment Editor: Fix showing cached variables instead of synced ones

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_voice.lua

Fixes #953. I couldn't test this, because I only have bots to test. One thing I noticed was that the global chat opened a UI element, the team chat didn't. I don't know if this is a new bug? But I can't see what is causing this. Might be a good idea to verify this fix before merging.

Voice: Removed Voicerecord Command

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_addonchecker.lua

This fixes the addon compatibility detection so that only enabled/mounted addons are checked against the incompatible list.

Addon Checker: Added Mounted State Checking

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
lua/terrortown/menus/gamemode/administration/hud.lua
lua/terrortown/menus/gamemode/appearance/hudswitcher.lua
lua/terrortown/menus/gamemode/appearance/vskin.lua
lua/terrortown/menus/gamemode/equipment/base_equipment.lua
lua/terrortown/menus/gamemode/language/language.lua
lua/terrortown/menus/gamemode/shops/base_shops.lua

Okay, Im gonna test those now, but you can already give feedback to the whole restructuring 😄 
Changelog below:
- Reworked our simplified Dropdowns MakePanel `PANEL:MakeComboBox(data)` version
- Added possibility to manipulate serverside ConVars with Dropdowns. Just add .serverConvar with the conVarName to the given data similar to .convar
- .serverConVar and .conVar are also supported
- data.choices can now be a table containing `{title, value, select, icon, additionalData}`
- data.selectValue is added, use it instead of data.selectName to choose the value you set
- data.selectTitle is added and shall replace data.selectName
- Reworked Dropdowns Panel `DComboBoxTTT2` itself
- `PANEL:AddChoice(title, value, select, icon, data)` now uses the second argument as value string for setting …

Panel Dropdown: Added ServerConVar and reworked whole structure

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/base_ammo_ttt.lua

Base Ammo Entity: Fix collision bounds blocking +use traces by using trigger bounds instead

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_admin.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/server/sv_player_ext.lua
gamemodes/terrortown/gamemode/shared/sh_main.lua
lua/terrortown/menus/gamemode/base_gamemodemenu.lua
lua/ttt2/extensions/cvars.lua
lua/ttt2/libraries/entspawnscript.lua
lua/ttt2/libraries/playermodels.lua

```lua
---
-- A hook that is called whenever the gamemode needs to check if the player is in the superadmin usergroup.
-- This hook can be used to allow custom usergroups through these checks.
-- @note This hook grants access to powerful functionality, such as the gamemode configuration, damage logs and player role information. Only allow usergroups that absolutely need such access.
-- @param Player ply The player to be checked
-- @return boolean if the player is a valid usergroup
-- @hook
-- @realm shared
```
- Hook was added in `sh_main.lua` as it was the best place I could find for such a hook. If anyone else knows of a better spot for it, please tell me.
- Hook will return `ply:IsSuperAdmin()` by default.

Security: Add new GM:TTT2AdminCheck hook, replace all IsSuperAdmin() checks with hook

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player.lua
lua/terrortown/lang/en.lua
lua/terrortown/menus/gamemode/administration/playersettings.lua

- `ttt2_falldmg_enable (default: 1)` toggles whether or not to apply fall damage at all
- `ttt2_falldmg_min_velocity (default: 450)` sets the minimum velocity threshold for fall damage to occur
- `ttt2_falldmg_exponent (default: 1.75)` sets the exponent to increase fall damage in relation to velocity
All ConVars listed above can also be adjusted in the F1 -> Administration -> Player Settings menu.

Fall Damage: Add ConVars to allow customization for server admins

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

When a role change leads to a team change the hook call is made twice.
Due to some roles being able to change teams without changing role (e.g. pirate captain) we need the call in both functions, so we suppress it in the updateTeam call if necessary.
Should solve #979

Role Changes: Fix double TTT2UpdateTeam hook call on role change

---

.github/workflows/cd.yml

Currently the concurrency leads to a maximum of one active deployment
and one pending deployment.
If a pending deployment already exists and another gets requested the
already existing pending deployment fails. In case of two PRs being
updated this would mean that the PR which is updated first would be
impossible to deploy.
Originally i intended to use the concurrency to prevent a singular PR
from creating multiple pending deployments. While this should still be
possible by using a concurrency group unique to the PR, there is also
the possibility that the default behaviour for deployments on environments
is already doing what i want.
Which is why my current approach is to remove the stanza completely.
Sadly the github documentation on this is severely lacking IMO.

cd: Remove 'concurrency' stanza from deploy job

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_spawninfo_ent.lua

Fixed the spawn editor TargetID not showing by always rendering the "ttt_spawninfo_ent" Entity.
The Added function will now always render the entity for players, not only when needed. Without this, the entity gets culled and the TargetID stops working.

Fixed: Spawn editor TargetID not showing

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_roleselection.lua

With the help of bud, we identified a problem where not every role could be chosen.
Randomize base role selection and stop after maxRoles was reached or every role chosen.

Roleselection: Fix not every role could be chosen

---

CHANGELOG.md
lua/terrortown/lang/pt_br.lua

Seems like the change from `itemeditor` to `equipmenteditor` got lost somewhere.
While at it i also added the remaining untranslated strings as comments.

Language: Fix some language identifiers for portuguese

---

.github/workflows/cd.yml

The key difference here is that `pull_request` only allows PRs originating from branches of the original repository to access secrets while `pull_request_target` also allows this for PRs originating from forked repositories.
While this is potentially unsafe [1] (which i was aware of when i first added the cd workflow with the intentation that this would already work) it is safeguarded by someone having to manually approve the workflow run (currently only myself).
Using the `permissions` keyword [2] should allow to limit the scope further without restricting the access to the secrets. (At least i hope this is the case, because the github documentation is rather unclear on this IMO).
[1] https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
[2] …

cd: Fix `deploy-to-dev` workflow not running on PRs from forks

---

CHANGELOG.md
lua/terrortown/menus/gamemode/guide/equipment.lua
lua/terrortown/menus/gamemode/guide/gameplay.lua
lua/terrortown/menus/gamemode/guide/roles.lua

This change adds a small message to inform players, that the content here is still missing and we are happy about contributions. 
This should avoid users getting confused when seeing empty panels.

guide: Add placeholder text to empty panels

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua

- Removed `SWEP.IronSightTime` as it lacked any use within the gamemode, and was redundant as ironsight times are already managed with networked data tables
- Fixed `SWEP.IronSightPos` to `SWEP.IronSightsPos` for both a) consistency with literally every other SWEP and function using the latter variable names, and b) because it was breaking the ironsights of any SWEP trying to use the default values inherited from `weapon_tttbase`.

SWEPs: Slight fixes to weapon_tttbase

---

CHANGELOG.md
lua/ttt2/libraries/roles.lua

Not sure what we lose by not using stored values, but I can't see where it would be useful.
Currently it's doing more harm than good.

Roles: Fix hotreload (again!)

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_wepswitch.lua

ttt_quickslot did not work previously.
QuickSlot wrongly tried to convert the args table to a number.
There was also a mix up between slots and weapon kinds: The current weapon kind is already the same as the displayed number, no need to subtract 1 from user input.

fix ttt_quickslot

---

.github/workflows/ci.yml
.github/workflows/main.yml

Github deprecated support for actions that run on node.js 12 [1]. So we update the affected actions to a version that uses node.js 16.
Glualint was also some versions behind so i've updated it as well, including the changed download url.
[1] https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

ci: Update actions and glualint

---

.github/workflows/cd.yml

While this was certainly good to try out for a bit it certainly had multiple problems. Which i want to touch upon.
Before that, the reason for not removing the workflow file completely is to keep this as a reference if we want to use this in the future for maybe deploying the master branch on our public testserver.
Now to the problems:
1. I was the only one actually using this. That is fine, but this way it makes sense to (semi)automate this differently. Which i have done now (not public, sorry).
2. The way this deploys the pull request branch is not super resistent against my tinkering on that server and has broken before. Not that much of a problem but leading to a failed workflow on the PR which brings me to my third point.
3. Terrible user experience for contributors who are opening a …

cd: Remove dev deployment on pull requests

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
gamemodes/terrortown/gamemode/shared/sh_shopeditor.lua
gamemodes/terrortown/gamemode/shared/sh_sql.lua
lua/terrortown/lang/en.lua
lua/terrortown/menus/gamemode/administration/randomshop.lua
lua/terrortown/menus/gamemode/equipment/base_equipment.lua
lua/ttt2/libraries/database.lua

- adds a new data type "float" for the network
- adds a new data type "float" backed by REAL for SQLite
- adds a new data type "float" for the options
- decimal handling optional
- changes randomshop also but nothing there uses it, for parity

Damage Scaling added to Equipment's Balance Settings

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_targetid.lua

Fixed the two ConVars "ttt2_enable_spectatorsoutline" and "ttt2_enable_overheadicons" being used with two different names and thus not working
In cl_targetid the old values "ttt2_cvEnableSpectatorsoutline" and "ttt2_cvEnableOverheadicons" were used.

Fixed: Unmatched performance ConVars

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player.lua

tested it for a few rounds
admin wallhacks indicate that the spectator ghosts tend to remain where they get warped on death

cvar ttt2_bots_lock_on_death fixes #1043

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_roleselection.lua

lets people mess with things without having to blast role distribution and reset models and credits in TTTBeginRound

last minute role change hook

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua

after, before, the code in question

passes name of panel down for comparing with GetName()

---

CHANGELOG.md
lua/ttt2/libraries/entspawn.lua

The results are similar, sometimes but the semantics differ. In this case, the final random parameter was so future-proofed that it failed to distinguish itself. Maybe a jargon file of some form would help?

Random Ammo Spawn Issue, fixes #1049

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_changes.lua
gamemodes/terrortown/gamemode/shared/sh_init.lua

Release latest changes.
Includes the changelog and version bump according to the release process documentation.

[Release]: v0.11.7b

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_traitor_button/init.lua
lua/ttt2/libraries/entspawnscript.lua

not tested extensively, feature still in dev for gmod itself

allow reading files from data_static

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenulist_ttt2.lua
lua/ttt2/extensions/util.lua

Changed how the textbox for sliders work. You can now klick on them to make changes directly via input. WIP
Demonstration:
https://cloud.nickcloud.at/index.php/s/NEXjr8SCfnC5jdc
Currently the textbox does not allow to go below the minimum, but above the maximum. Should I change it so both is disallowed? Or maybe that both is allowed to have more fine tuning?
Also the function "getHighestParent": Maybe this should move to a global function?
Currently the text box is not very pretty, but I actually have to idea right now on how to make it prettier..
Open for all ideas.
Changelog will follow at last.

[WIP] Added: Slider text area for values

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_voice.lua
gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua
lua/terrortown/lang/de.lua
lua/terrortown/lang/en.lua
lua/terrortown/lang/es.lua
lua/terrortown/lang/fr.lua
lua/terrortown/lang/it.lua
lua/terrortown/lang/ja.lua
lua/terrortown/lang/pl.lua
lua/terrortown/lang/pt_br.lua
lua/terrortown/lang/ru.lua
lua/terrortown/lang/zh_hans.lua
lua/terrortown/lang/zh_tw.lua
lua/terrortown/menus/gamemode/gameplay/general.lua

I think there should be hooks in here somewhere so equipment like the Mute Radio can continue to exist, but I'm not sure where.
I don't know if I make note of it specifically but bots report distinct values for SteamID64 so that workaround isn't necessary anymore.
problems:
- if someone dies while talking, once their audio becomes non-3D their volume should be changed prior to that, but presently I don't know where that happens, because the name-plate stays team-colored until they finish talking.
- also the dropdown selector raises errors for me if changed several times which I believe is just an issue that already existed, the convar still functions

voice volume scaling / spectator ducking

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua

Fixes #1068
We need to remove the callback in a timer, because otherwise the ConVar change callback code
will throw an error while looping over the callbacks.
This happens, because the callback is removed from the same table that is iterated over.
Thus, the table size changes while iterating over it and leads to a nil callback as the last entry.
See https://github.com/Facepunch/garrysmod/blob/1b512930d1f8fb1acf6235e584c4ec1ff84e9362/garrysmod/lua/includes/modules/cvars.lua#L44
and
https://github.com/Facepunch/garrysmod/blob/1b512930d1f8fb1acf6235e584c4ec1ff84e9362/garrysmod/lua/includes/modules/cvars.lua#L97
here the code uses table.Remove, which causes the table to be reindexed and resized, this is the root cause for the problem.
We should thus avoid removing callbacks in the callback …

fix: Combobox ConVar change callback deletion

---

CHANGELOG.md
lua/terrortown/menus/gamemode/language/language.lua

Fixed the percentage in F1 menu displaying the wrong number.
Seems like just removing the check fixes the issue.. Although the VGUI will refresh even if selecting the same language again.. But I think thats not really a big deal.

Fix: F1 translation percentage

---

gamemodes/terrortown/entities/entities/ttt_c4/shared.lua
gamemodes/terrortown/entities/entities/ttt_health_station.lua

After the removal of `AccessorFuncDT()` some accessors might be using a local var instead of the network var. With this change this should be fixed again.
We shouldn't use `ENT:DTVar()` in general and instead use `ENT:NetworkVar()` as that also correctly creates the necessary accessors.
Thanks @EntranceJew for noticing.

fix: Make sure accessors use DTVars

---

gamemodes/terrortown/entities/entities/ttt_c4/shared.lua

I failed to see that with the old `AccessorFuncDT()` call it was possible to influence the accessor function names which resulted in accessors that were cased differently than their respective networked vars.
This renames the networked vars which shouldn't itself matter as the vars should only ever be accessed via their accessors anyway.

fix: Correct network var names

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_propspec.lua

Reworked the propspec inputs to be more predictable. The old implementation was really janky and did not take into account in which way the player is looking, see #1093 
I also removed the angular force, because I'm pretty sure it was only added to "fix" the broken implementation.

Prop Possesion: Made input directions more intuitive

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua
gamemodes/terrortown/entities/weapons/weapon_zm_pistol.lua
gamemodes/terrortown/entities/weapons/weapon_zm_revolver.lua
gamemodes/terrortown/entities/weapons/weapon_zm_sledge.lua
gamemodes/terrortown/gamemode/server/sv_player.lua
gamemodes/terrortown/gamemode/server/sv_player_ext.lua
gamemodes/terrortown/gamemode/shared/sh_door.lua
gamemodes/terrortown/gamemode/shared/sh_main.lua
lua/ttt2/libraries/plyspawn.lua

This reverts commit 917d9c1c90651971eb71754bb6cf3bdd5745b5a4.
#	CHANGELOG.md

Revert "use global vectors, especially inside those loops"

---

lua/terrortown/lang/es.lua
lua/terrortown/lang/fr.lua
lua/terrortown/lang/it.lua
lua/terrortown/lang/ja.lua
lua/terrortown/lang/pl.lua
lua/terrortown/lang/pt_br.lua
lua/terrortown/lang/ru.lua
lua/terrortown/lang/sv.lua
lua/terrortown/lang/uk.lua
lua/terrortown/lang/zh_hans.lua
lua/terrortown/lang/zh_tw.lua

Over the time some language strings changed. But this change was not applied to all languages. Since our new language tool is able to spot these, it was easy to fix them.
I also noticed a few errors that I could fix without removing the strings (missing brackets, wrong var names etc)

[Lang] Cleaned up Language with Param Translation

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua

For the new style only 1 tostring (for choice.value) is enough.
For the "old simple structure" we need a tostring for choice in general or it might error when mixing strings and integers as values because of the sorting methode.
Addresses: https://github.com/TTT-2/TTT2/issues/1071

Fix: ComboBox integer values not working

---

CHANGELOG.md
lua/ttt2/libraries/none.lua

Seems like a few other addons are using this function and removing it causes them to break. So we will deprecate it instead and give addon developers a chance to update their addons.
Sadly i have not found a good way to log which addon is still using this. Using `ErrorNoHaltWithStack()` will show the addon in the stacktrace but it will also be presented to players as "The addon 'TTT2' is causing errors".
So i went with `MsgN()` for now.

fix: Deprecate `AccessorFuncDT` instead of removing it

---

gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua

Since the database rework #984, the slider textbox was causing errors and lead to an unusable shop per map.
This was because the textbox directly called the SetCallbackEnabledVarValues with a string, which is not handled by the database approach, but worked for convars.
Also optimized the textbox interaction:
- `OnEnter` also calls `OnLoseFocus`, so I removed it
- IsEditing now uses the new Textbox-Check
- Therefore no extra call to SetCallbackEnabledVarValues needs to be done

VGUI: Fix slider textbox

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/hud_elements/tttminiscoreboard/pure_skin_miniscoreboard.lua

mini scoreboard kept showing confirmed players that became spectators as revived, which is wrong
video of before / after fix hotreloads:
https://github.com/TTT-2/TTT2/assets/5711436/baf1a083-4165-4a17-9395-550735f2e903

Mini Scoreboard Confirmed Spectator Fix

---

.github/workflows/ci.yml

This should fix our current neodoc ci failure
(or rather prevent it from happening again)

ci: Bump neodoc version to fix workflow error

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_game_text.lua

PR #1006 tried to simplify the gametext entity. While doing so it changed many things that break the functionality. This one is on us for being to lax while reviewing it. Most of these changes should not have been done.

revert most of the change from #1006

---

gamemodes/terrortown/gamemode/shared/sh_init.lua

Fixed missing fastutf8, found that there seems to be something missing to introduce it correctly causing the error in the picture to occur when pressing F1 or pressing TAB after already using Chinese.

Fix missing fastutf8

---

lua/ttt2/extensions/draw.lua

Also removes an unnecessary call to GetTextSize.

Draw: Fix wrong width parameter for split long word

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/hud_elements/tttminiscoreboard/pure_skin_miniscoreboard.lua
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

@EntranceJew added a spec check in #1157. This causes issues if the player entity is null that were previously ignored. I added a validity check here.
I also moved the Spec check into the existing function, so all HUDs (e.g. octagonal) have this fix as well

Fix #1171, undefined entity after a player disconnected

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_radio.lua
lua/terrortown/lang/de.lua
lua/terrortown/lang/en.lua
lua/terrortown/lang/es.lua
lua/terrortown/lang/fr.lua
lua/terrortown/lang/it.lua
lua/terrortown/lang/ja.lua
lua/terrortown/lang/pl.lua
lua/terrortown/lang/pt_br.lua
lua/terrortown/lang/ru.lua
lua/terrortown/lang/sv.lua
lua/terrortown/lang/tr.lua
lua/terrortown/lang/uk.lua
lua/terrortown/lang/zh_hans.lua
lua/terrortown/lang/zh_tw.lua

Old PR: [Removed restriction that only team can pickup Radio](https://github.com/TTT-2/TTT2/pull/1204) 
Original issue: #1125
> - replace the key in that case with a radio icon, feel free to hit me up for an icon
I feel this should be the +use key crossed out, to show that it can be picked up, just you cannot pick it up

Radio: Only owner can pickup

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_beacon.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
lua/terrortown/lang/de.lua
lua/terrortown/lang/en.lua
lua/terrortown/lang/es.lua
lua/terrortown/lang/fr.lua
lua/terrortown/lang/it.lua
lua/terrortown/lang/ja.lua
lua/terrortown/lang/pl.lua
lua/terrortown/lang/pt_br.lua
lua/terrortown/lang/ru.lua
lua/terrortown/lang/sv.lua
lua/terrortown/lang/tr.lua
lua/terrortown/lang/uk.lua
lua/terrortown/lang/zh_hans.lua
lua/terrortown/lang/zh_tw.lua

TTT has a disabled item called "Beacon". Its use is pretty limited and was therefore disabled. While working on the entity bringdown vol2 I got an idea on how to add some fun to this weapon:
The beacon is now a "live-radar" that only works in a small-ish sphere. It uses the marks module for this:
Once a player walks out of this sphere, the wallhack is removed again.
The owner of the beacon is also informed about two events:
- a player died next to their beacon
- one of their beacons was destroyed

Beacon: Rework

---

CHANGELOG.md
lua/terrortown/entities/items/item_ttt_radar/shared.lua

seems to work fine,
https://github.com/TTT-2/TTT2/assets/5711436/3c0b26e4-b48c-46a7-985a-cbc0d755f5b9
i don't think there's a way to trigger a decayed removal 'cause all the timer logic is server-sided, and there's not a net message to wipe it later

RADAR: Clear when removed, fixes #1070

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_game_text.lua

logically, it doesn't address innocents
it has always referred to everyone but traitors
refer to:
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/terrortown/entities/entities/ttt_game_text.lua#L48-L49
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/terrortown/gamemode/gamemsg.lua#L83-L85
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/terrortown/gamemode/player_ext_shd.lua#L14-L17

ttt_game_text mode 4 correction (fixes #972)

---

CHANGELOG.md

Well, I made a mistake with the last merge. I resolved the conflict, but the entry was still for the old release. Added the other categories as well.

Changelog: Move entry to correct position

---

CHANGELOG.md
lua/ttt2/libraries/keyhelp.lua

Fixes #1246 by hiding the keyhelp when voicechat is disabled.

Keyhelp: Check if voicechat is enabled

---

lua/ttt2/libraries/keyhelp.lua

The current code fails when no element is in any of the key help tables. This went unnoticed when testing, because all tables have enties by default.
This is still bad because the UI code fails if a user decides to remove the disguiser from the sourcecode for example.

Keyhelp: Fixed nil-table indexing

---

CHANGELOG.md
lua/ttt2/libraries/targetid.lua

designed to fix situations like this one:
(normally it'd show a yellow toetag because i didn't search it, and the police didn't search it)

targetid show role of named corpses

---

CHANGELOG.md
lua/ttt2/libraries/targetid.lua

you still can't check their roles from the `was_role` property because someone has to make that info available to the client
demo of the difference, the 2nd corpse would cause a crash:
https://github.com/TTT-2/TTT2/assets/5711436/23bb4363-886b-4b4c-8510-606f17add8ed

Corpses: Fix looking at disconnected player's corpses

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
lua/ttt2/extensions/draw.lua
lua/ttt2/libraries/keyhelp.lua

Added scaling to keyhelp and weapon HUD help elements. I also slightly tweaked how shadows are calculated in the draw library to prevent weird glitches at some scale values

HUD-help Elements: Use global scale factor

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/shared/sh_main.lua

Fixed `TTT2FinishedLoading` hook not called on server on hot reload, also added a docstring.

Fixed TTT2FinishedLoading hook not called on server on hot reload

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dlabel_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dnumslider_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dpanel_ttt2.lua
lua/terrortown/menus/gamemode/administration/entspawn.lua
lua/terrortown/menus/gamemode/administration/karma.lua
lua/terrortown/menus/gamemode/administration/mapentities.lua
lua/terrortown/menus/gamemode/administration/playersettings.lua
lua/terrortown/menus/gamemode/administration/roles.lua
lua/terrortown/menus/gamemode/administration/roundsetup.lua
lua/terrortown/menus/gamemode/equipment/base_equipment.lua

Subsettings are now indented to make it easier to spot which settings are related. The master/slave and enable/disable system was also added to helpboxes.

Indent Subsettings

---

CHANGELOG.md
lua/ttt2/extensions/debug.lua

While debugging the shopeditor, I noticed, that `nil` entries make an otherwise sequential table to be not sequential.
For example this:
`{"The value of", key, "is",value,""}`
is now shown as:
`"The value of" "Kind" "is" nil `
before it was shown with the fourth entry being empty:
```
1:"The value of"
2:"Kind"
3:"is"
5: 
```
But it still cant handle nil entries at the end of a table. So this:
`{"The value of", key, "is",value}`
will still be shown as:
`"The value of" "Kind" "is" `

Debug: Enable nil entries in nearly sequential table

---

CHANGELOG.md
lua/ttt2/libraries/database.lua

With the new way to get all weapon stats at startup, they are automatically cached.
When accessing that cache per key, the values are `nil`, even if they are marked as received.
Thats because the new system saves default values as `nil` in the database and deletes them if the complete weapon is default.
To fix that, it now always returns the correct values in the GetValue-function.
Downside is, that tables are synchronized with values instead of `nil`/no entry for values that are defaut anyway.
That makes synchronization slower.
Better would be to abstract it further and have a separate Get-Function for internal synchronization and external retrieval.
So that in case of synchronization only changed values are synced, but when retrieving them default values are automatically inserted and …

Shopeditor: Fix missing default values for nil entries

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player_ext.lua

TTT2 has the ability to remove and cache a player's inventory to be later given back to the player. It is also designed to autoselect the old weapon. However this was broken all the time.
I solved this issue here with a 100ms timer. I don't like this hook, but I spend at least two hours trying to solve the underlying issue here but I was unable to. My best guess is that it has to do something with prediction as weapon selection aparantly is predicted. Adding a 100ms delay between giving and selecting weapons solved the issue for me.
Things I tried that also failed:
- running `lastinv` on the client
- using `input.SelectWeapon` on the client as this function is predicted

Added Delay to Weapon Select

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_unarmed.lua
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
gamemodes/terrortown/gamemode/client/cl_hudpickup.lua
gamemodes/terrortown/gamemode/client/cl_player_ext.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/server/sv_player_ext.lua
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
lua/ttt2/libraries/entspawnscript.lua

While working on TTTC I noticed some issues with weapon caching and fixed them in this PR. I also added the same caching for items.
Things I did in this PR:
- fixed weapon caching
- set missing `builtin` flag
- fixed an item syncing issue with table remove
- added `weapon_ttt_unarmed` to base
- made sure that by default a player keeps `weapon_ttt_unarmed` when removing all their weapons to keep the crosshair etc
- added flag for weapons to hide pickup notification and added this flag to `weapon_ttt_unarmed`

Improved Weapon Caching

---

CHANGELOG.md
lua/ttt2/extensions/draw.lua
lua/ttt2/extensions/surface.lua

I added the circle draw code from TTTC to TTT2, cleaned it a bit up, added docs and support for shadowed arcs.
Circle draw Code in TTTC: https://github.com/TTT-2/TTTC/blob/15b34a8d75067550a46811af687ab4979ef34847/lua/terrortown/autorun/client/cl_classes_hud.lua#L132-L233

Added Circle Draw Code from TTTC

---

CHANGELOG.md
lua/ttt2/libraries/database.lua

Apparently I forgot to properly check if all settings are saved to the database.
When saving false values, they got converted to nil, which got interpreted by the database as default value.

Database: Fix boolean conversion

---

gamemodes/terrortown/entities/weapons/weapon_ttt_unarmed.lua
gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua
gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua

this is a stopgap until either:
1. AllowDrop controls all droppability such as idle drop, death drop, and most significantly, swappability (you cannot swap melee weapons unless you either have 2 melee slots or enable AlowDrop on the crowbar)
2. overrideDropOnDeath overrides all drop situations including idle drop , in addition to death drop
3. AllowDropOnDeath flag implemented preventing weapons from dropping on death but still being swappable/droppable
4. a more robust solution that involves some hierarchy of DROP/SWAP /REPLACE (allow picking up a melee slot item, but destroying the original crowbar)/DESTROY/ON_DEATH that i can't articulate
there is also the potential restriction that default-loadout items should be destroyed instead of dropped but that would potentially impact TTTC more …

prevent dropping weapons that ordinarily are not droppable on death

---

gamemodes/terrortown/gamemode/client/cl_main.lua

if someone has developer 1 on then they can see that an event which triggered a full state rebroadcast, aka, someone's role changed

do not leak SendFullStateUpdate events happen

---

CHANGELOG.md
lua/ttt2/libraries/marks.lua

This PR addresses the marks library having self zfailing and color issues.
This originated from helping @TimGoll on the [gmod discord](discord.gg/gmod) with this issue, more context can be found [there](https://discord.com/channels/565105920414318602/567617926991970306/1200805871303786506)
For completeness sake i will also mirror his original help request here:
```
It is me again, this time with a more in depth question about stencils and rendering. It is about this part in our TTT2 codebase: https://github.com/TTT-2/TTT2/blob/master/lua/ttt2/libraries/marks.lua#L76-L108
It is used to render "marks" (or wallhacks) of an entity through a wall (see picture 1)
But there is a problem. We color the entity with ent:SetColor on spawn to the player's role color. The entity itself is white. This …
```

Fix issues with marks library

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_targetid.lua
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

This PR brings multiple small and minor improvements to the over head icons:
- they track the head bone positions: This means they move with the player animation, move down when crouched and also change position when the model scale is changed (i.e. when the minifier is used)
- it now uses a proper Cam3D2D environment: This fixed some minor issues with the icon drop shadow
- rendering order is based on distance: Previously the icons were drawn in the player order which could cause icons to be rendered in front of icons that they shouldn't be; it is now sorted by distance
- when observing a player in their eyes, their icon is now hidden, it is still shown when in third person
- changed the angle the icon is drawn: the rotation is still the same, but the pitch is locked on 90 meaning that …

Over Head Icon improvements

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/sh_init.lua
lua/ttt2/extensions/render.lua
lua/ttt2/extensions/surface.lua

Thanks to @WardenPotato we now know that [we have to reset the stencils](https://github.com/TTT-2/TTT2/pull/1267#issuecomment-1913711414) between each poly draw.

DrawArc: Added Stencil Reset

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua

Similar to #1353 now the DNA scnanner uses meters:

DNA Scanner Now Uses Meters

---

gamemodes/terrortown/entities/weapons/weapon_tttbase.lua

Due to math.floor crosshairs were invisible for scales smaller than 1, math.ceil fixes this issue

Fixed Crosshair for Scales smaller than 1

---

gamemodes/terrortown/gamemode/client/cl_lang.lua

This should not show users that TTT2 has errors and will only be useful for developers.

Debug: Reduce severity of lang identifier warning

---

CHANGELOG.md

These were moved to a released version on resolving a merge conflict. Fixed this.

Changelog: Move wrongly placed entries

---

gamemodes/terrortown/entities/entities/ttt_basegrenade_proj.lua

This base class call doesn't do anything here and also causes an error.

Grenades: Removed BaseClass init

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_targetid.lua

vs
does not affect propspec nametag because that helps find the prop's origin

TargetID: Disable seeing own spectator nametag

---

CHANGELOG.md
lua/terrortown/entities/items/item_ttt_radar/init.lua

This fixes and issue with the radar showing a grey radar symbol instead of the green one for other teams.
I'm not sure, but was this just an oversight or am I just not seeing something else that may cause this issue?
Setting the team to TEAM_INNOCENT too fixes the issue.

Fix: Radar decoy fix

---

gamemodes/terrortown/gamemode/client/cl_player_ext.lua
gamemodes/terrortown/gamemode/server/sv_player.lua
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

This PR fixes an issue with the synced player settings. Initializing the synced player settings as `plymeta.playerSettings = plymeta.playerSettings or {}` results in one table reference being created that is shared between all instances of the `Player` class. This pullrequest changes this so that each player has their own instance of said class.

Playersettings: Fixed unwanted shared rederence

---

CHANGELOG.md
lua/ttt2/libraries/targetid.lua

Door health is a float internally, but it should not be displayed that way to the clients. `math.ceil` was chosen to prevent the door showing "0 HP" and still existing.

Doors: Added rounding to door health

---

gamemodes/terrortown/entities/entities/ttt_beacon.lua
gamemodes/terrortown/entities/entities/ttt_c4/cl_init.lua
gamemodes/terrortown/entities/entities/ttt_radio.lua

Due to an auto merge issue, the originator got wrongly reset to the owner. This PR fixes this. This also fixes marker vision not working and the radio not making any sounds.

EntityBase: Changed Owner to Originator

---

gamemodes/terrortown/gamemode/server/sv_addonchecker.lua

As described in #1406 the added addon breaks our random spawn system and is therefore incompatible.

Addonchecker: Added another addon

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
gamemodes/terrortown/entities/entities/ttt_beacon.lua
gamemodes/terrortown/entities/entities/ttt_cse_proj.lua
gamemodes/terrortown/entities/entities/ttt_decoy.lua
gamemodes/terrortown/entities/entities/ttt_radio.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
lua/terrortown/lang/en.lua

I added pickup handling to the recently added entity base.
To add this to an entity, the following two parameters have to be set:
```lua
ENT.CanUseKey = true -- to enable the ENT:UseOverwrite hook
ENT.pickupWeaponClass = "weapon_ttt_radio" -- to define which weapon should be added to the inventory
```
There are two hooks that are called during the pickup process:
```lua
---
-- Run if a valid player tries to pick up this entity to check if this pickup is accepted.
-- @param Player activator The player that used their use key
-- @return[default=true] boolean Return true to allow pickup
-- @hook
-- @realm server
function ENT:PlayerCanPickupWeapon(activator)
```
```lua
---
-- Called when this entity is picked up and about to be removed.
-- @param Player activator The player that used their …
```

Entity Base: Added Pickup Handling

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_ttt_beacon.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_c4.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_decoy.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_health_station.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_knife.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_phammer.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_radio.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua

While fixing bugs in weapons I was pretty annoyed about two things:
- many weapons forget to call `lastinv` on remove, meaning that you don't have a weapon selected, not even unarmed (e.g. when placing a boom body the boom body placer weapon is removed)
- fixing this means copying the same code to each weapon
Therefore I added it to the weapon base with a SWEP flag to disable it if desired. But I don't see a reason why you wouldn't want it, my testing showed no problems.

Weapon Base: Auto select last weapon on remove

---

gamemodes/terrortown/gamemode/shared/sh_shop.lua

Apparently this check moved out of the function everytime the team is not none and not alone, therefore nearly always.
Also fixing the return type, which is just void.
Does now only skip a table entry if there is no team, or team_none or alone.

Shop: Invert internal Team buy check

---

gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
gamemodes/terrortown/gamemode/server/sv_player_ext.lua
lua/terrortown/lang/en.lua

Previously you were always able to throw devices (beacon, radio etc). This could cause issues when really close to a wall as they would glitch through it. I added the same check to it, that the weapon dropping also uses.
While working on that I decreased the min distance to a wall when dropping a weapon as I noticed that a smaller distance works as well and improves the weapon pickup in tight corners. My testing also showed no glitches with this change.
This should fix the issue @mexikoedi was having.

Entity Base: Added throw space check

---

lua/ttt2/libraries/weaponrenderer.lua

Fixes #1415 
When weapons with a custom world model are dropped, the renderer tries to render them but fails because it was unable to find the relevant bone and therefore exits early. This is not a problem when the entity has an owner (mostly the player holding that weapon) because the player entity has the required bone if the weapon is set up properly.
This PR fixes this issue by introducing a fallback to render it in place when the weapon has no owner by using its own main bone (which can have any random bone name).
Additionally I noticed the hitboxes of the models were completely off after I fixed the rendering issue. This is because we apply render filters clientside to the model that only change its appearnce, not its actual entity. This is not an issue for custom world or view …

Custom World Models: Fixed rendering for custom world models

---

CHANGELOG.md
lua/terrortown/menus/gamemode/equipment/base_equipment.lua

Last night I discussed some things with @mexikoedi. One thing we noticed that there are quite a few badly done weapons for TTT that forget to set the weapon base correctly. While this is bad practice and shouldn't be done, most of these weapons still work just fine. Adding this check here makes sure that this populate function is only called if it actually uses the correct base.

EquipmentMenu: Added check before function call

---

gamemodes/terrortown/entities/weapons/weapon_ttt_unarmed.lua
lua/terrortown/menus/gamemode/equipment/base_equipment.lua

Currently it is possible for weapon_ttt_unarmed to be dropped, but as it is no real weapon it's not inside the shopeditor, therefore settings made to it via mysterious ways cant be reversed.
One example are the wrongly saved values to the database introduced in v0.11.7b with this PR #1041.
As only in v0.12.0b with PR #984 the way no default values are saved was introduced, servers before this PR now have partly unusable values saved for some weapons and changing their defaults now doesnt change that anymore.
So this partly reverts changes done in #1310  at least for unarmed.
To make sure this never has any consequences on other weapons we also block the ability to choose the unarmed slot.

Equipment: Always remove weapon_ttt_unarmed

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_equip.lua
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/client/cl_shopeditor.lua
gamemodes/terrortown/gamemode/shared/sh_main.lua
lua/terrortown/menus/gamemode/equipment.lua
lua/terrortown/menus/gamemode/shops/base_shops.lua

Fixes #1403 
Partly fixes some of #1091 (it does not fix this issue, it fixes a part of this issue, but after hotreload weapons are still missing (items are there) and everything is not buyable)
It looks like lots of changes, but I only moved things around. It is mostly the old code with renamed variables split into three functions. Notable changes:
- caching is now independant of eject and other changes, meaning that also `weapon_ttt_unarmed` has a cached icon
- caching now happens on every load / reload of the game instead of the first call this improved the first opening time of the shop for me by a lot
- it fixes the issue that the cache is not rebuilt on hoteload until the shop is reopened, improving some things mentioned in in 1091

Equipment Caching: Rework

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player_ext.lua

There was a typo in a debug message which caused the following error.
```
[TTT2 (Base) - v0.13.0b] gamemodes/terrortown/gamemode/server/sv_player_ext.lua:239: attempt to call global 'ErrorNoHaltWithStackWithStack' (a nil value)
1. SendEquipment - gamemodes/terrortown/gamemode/server/sv_player_ext.lua:239
2. ForceAddEquipmentItem - lua/autorun/sh_lastmanstanding_init.lua:240
3. OnLastManStanding - lua/autorun/sh_lastmanstanding_init.lua:189
4. unknown - lua/autorun/sh_lastmanstanding_init.lua:47
5. unknown - lua/includes/modules/concommand.lua:54
```
This is now fixed.

Fix for an error in a debug message

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/shared/sh_main.lua
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

- add plymeta:IsFullySignedOn
- overzealous AFK reigned in
now the player will not get booted the very moment they receive a role while joining or between rounds, as long as the idle_limit is greater than 5, the hardcoded check interval

AFK timer / incomplete player join bookkeeping

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
gamemodes/terrortown/entities/entities/ttt_radio.lua
gamemodes/terrortown/gamemode/client/cl_equip.lua
gamemodes/terrortown/gamemode/client/cl_tradio.lua
lua/terrortown/lang/en.lua

Before this you had to navigate to the shop tabs to use it, which is really unintuitive and currently blocks our idea to do a new shop.
Now you can use the 'Use'-Key from any distance on the focussed radio marker
and get the following new UI, which triggers the sounds in the same way as before
This will be waiting for the approval of the remote trigger feature in #1436

Radio: Create new UI for remote useable radio

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_radio.lua
gamemodes/terrortown/gamemode/client/cl_keys.lua
gamemodes/terrortown/gamemode/client/cl_marker_vision_data.lua
gamemodes/terrortown/gamemode/client/cl_targetid.lua
lua/ttt2/libraries/marker_vision.lua

Added the possibility to add a subtitle to marker vision
Also targetID is now hidden, when a marker vision element is focused as it is quite confusing to see two mutually exclusive use interactions on screen at the same time.

MarkerVision: Added subtitle option

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua

A crosshair is now also shown when holding a nade (not when the pin is pulled). This is done so you still know where to point when trying to interact with an entity.
I also removed the "select on remove" part, as this is in our weapon base since the last update.

Crosshair: Show for nades

---

gamemodes/terrortown/gamemode/client/cl_keys.lua
gamemodes/terrortown/gamemode/client/cl_tbuttons.lua

This PR fixes traitors sometimes not being able to use entities (doors, weapons, etc), and spectators not being able to use entities at all.
**Detail:**
Traitors were denied pressing Use on all entities except traitor buttons if they ever hovered their crosshair over a traitor button, as TBHUD:PlayerIsFocused would report they were always focused on one for the rest of the round.
_This has been fixed by adding a TBHUD.focus_stick check to TBHUD:PlayerIsFocused._
Spectators were permanently denied pressing Use. This was because the "pressed" parameter in GM:PlayerBindPress always returned false for spectators while the +use check inside it wanted "pressed" to be true in order to pass.
_This has been fixed by removing the "pressed" check for +use in GM:PlayerBindPress. The "pressed" …

Bugfix: Fixed issue with +use for traitors

---

CHANGELOG.md
lua/terrortown/entities/items/item_base/shared.lua
lua/terrortown/menus/gamemode/equipment/base_equipment.lua

This error was reported by @mexikoedi on Discord:
I fixed this by correctly using `WEPS.GetClass` here instead of `equipment:GetClass`. While doing this I noticed that items have no equivalent of `GetClass` and `IsValid` so I added that to the base class. These changes are not strictly needed for this fix, but imho they are useful for consistency.

EquipmentMenu: Fix GetClass error

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
lua/terrortown/menus/gamemode/equipment/base_equipment.lua

Fixes #1307 
Weapon settings:
Item settings:
Over time additions to the equipment menu did not take into account that these settings are mostly only relevant to weapons. So I added a check that hides settings that have no effect on items.

Equipment Settings: Item hide irrelevant settings

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua

The binoculars previously had custom crosshair rendering code. It now uses the same rendering code from the base that all weapons use.
old:
new (with custom color set in the settings):

Crosshair: Use default crosshair renderer for binoculars

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua

Fixes this issue reported by @EntranceJew and @mexikoedi:
The bug seen in the image happens because some weapons set a custom view model texture. Our view model hider resets this custom texture by calling `viewModel:SetMaterial("")`. I did not anticipate that weapons might set custom view models, so I wasn't aware that this is an issue.
We *have to* reset the view model texture because the view model does not change on weapon change. So if weapon A has a hidden view model and we apply the debug texture, the same debug texture is applied to weapon B making it invisible as well. The first solution of applying the texture reset if it should not be hidden caused the bug mentioned above.
The solution therefore is to set a trigger, if the debug texture is set before the view model is rendered …

ViewModels: Fix error texture bug

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua

doesn't make sense to do a dice roll for tracers in a deduction game, why let RNG play that part?

Weapons: Show trace for every bullet

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua

This started as a fix for a bug introduced in #1464 because HUD Help was now drawn twice for grenades with HUD help. So I decided to make the crosshairq function callable, so it can be called seperately in the grenade base.
While doing so I noticed [`SWEP:DoDrawCrosshair`](https://wiki.facepunch.com/gmod/WEAPON:DoDrawCrosshair). This function is called when `SWEP.DrawCrosshair` is set to true. We have set that to false in our base, because we do not want the GMod crosshair do be visible at all. However, some weapons set this to true, probably because the SWEP author thinks setting this to false disables the TTT2 crosshair. This results in two crosshairs being drawn at once:
In a perfect world we would use `SWEP:DoDrawCrosshair` to draw our own crosshair and then return `true` at the end. …

Crosshair: Prevent rendering GMod crosshair

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player.lua
lua/ttt2/libraries/bodysearch.lua

Noticed in 9cff5af that the hook run got re-added with the old name!
Used this opportunity to re-evaluate the hook, too. Decided to split it so that the original intention of the hook is intact whilst enabling the ability to handle the side effects of the hook.

bodysearch: TTT2GiveFoundCredits bugfix & new TTT2CanTakeCredits hook

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_main.lua

If a SWEP's CalcView function doesn't return the three expected values, DynamicCamera would spam errors and not function anymore.
This has been fixed by ensuring the active SWEP's CalcView returns valid values before giving them to DynamicCamera.

Fixed DynamicCamera breaking if a weapon's CalcView doesn't return complete values

---

CHANGELOG.md
lua/terrortown/menus/score/info.lua

Fixes #1456
Before this change the Roundendscreen showed karma changes even if karma was disabled:
To prevent confusion this change now prevents the Roundendscreen from showing these changes:

Roundendscreen: Don't show karma changes if karma is disabled

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_voice.lua
lua/terrortown/lang/de.lua
lua/terrortown/lang/en.lua
lua/terrortown/menus/gamemode/administration/chat.lua

Add locational voice chat range cut-off setting

---

CHANGELOG.md
lua/terrortown/lang/en.lua
lua/terrortown/menus/gamemode/administration/roles.lua
lua/ttt2/libraries/bodysearch.lua

The one question left for this is whether to change the default. Currently, this PR defaults to the previous behavior (all players can see credits, except in mode 2), but it seems to me like player expectations would favor not seeing credits by default.

Add convar to prevent players without credits from being able to see credits on a body

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_voice.lua
lua/terrortown/lang/de.lua
lua/terrortown/lang/en.lua
lua/terrortown/menus/gamemode/gameplay/voiceandvolume.lua
lua/ttt2/extensions/util.lua

- Push-to-Talk (default)
- Push-to-Mute
- Toggle
- Toggle (Activate on Join)
- Investigate how keeping voice chat activated interacts with rounds starting/ending
- The voice chat color should update accordingly. HUD-related changes should probably wait for #1473 though
- I think voice chat might currently get disabled once on round start (but your voice panel keeps being shown)
- Improve how team voice chat interacts with modes other than push-to-talk
- I didn't touch the TeamVoice functions which means that currently team voice can only be activated while global voice is off which is obviously silly for PTM/Toggle
- (Maybe have separate sections (forms) for input and output settings in the Voice & Volume menu)
- (Move ComboBoxChoicesFromKeys somewhere else since it's just a form creation …

Add multiple voice chat activation modes

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
gamemodes/terrortown/gamemode/client/cl_main.lua

1. Fixed player's FOV being stuck zoomed in if their weapon is removed while they're scoped in
2. Fixed FOV transitions being delayed in DynamicCamera when the player has lag, eg. when unscoping with a rifle

Bugfix: Fixed weapon FOV issues

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua

This fixes the following issue:
```
[TTT2 (Base) - v0.13.2b] gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:1054: Tried to use a NULL entity! 
1. MuzzleFlash - [C]:-1 
2. ShootBullet - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:1054 
3. PrimaryAttack - gamemodes/terrortown/entities/weapons/weapon_tttbase.lua:957 
4. unknown - lua/weapons/m9k_dbarrel/shared.lua:76
```
It should work and also makes the code more robust without creating new issues.
Reduces redundancy as well.

fixed null entity error

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua

This fixes the following issue:
```
[TTT2 (Base) - v0.13.2b] gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua:498: attempt to compare number with nil 
1. unknown - gamemodes/terrortown/entities/weapons/weapon_tttbasegrenade.lua:498
```
It should work and also makes the code more robust without creating new issues.
Reduces redundancy as well.

fixed nil compare error

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_targetid.lua
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

Sometimes overhead icons stayed stuck in the world. This is due to the way GMod/source handles player positions. If a player is far enough away, their position is no longer updated (as can be seen with wallhacks for example).
While `:GetPos()` still returns a position that at least represents a rough estimate of their position, the bone position stays at the last updated place. This means that the overhead icon stays floating in random places.
This pullrequest fixes this by introducing a check that uses the fallback position if the player position and the bone position diverge too much.
While I tested this, it would probably be good if @mexikoedi could confirm this as well.

HUD: Fixed OHI Desync

---

gamemodes/terrortown/gamemode/server/sv_addonchecker.lua

Added the Graffiti addon to the addonchecker because it causes multiple issue.
- It doesn't use the TTT base correctly
- It breaks playermodels if you throw the Graffiti away
- If you die while using it you will still hear the spray sound

Addonchecker: Added Graffiti

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dform_ttt2.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/shared/sh_init.lua
lua/terrortown/lang/en.lua
lua/terrortown/menus/gamemode/commands/commands.lua
lua/terrortown/menus/gamemode/commands/maps.lua
lua/ttt2/libraries/admin.lua

I added basic admin commands to the UI to restart the round, set the health etc

UI: Admin Commands

---

gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcombobox_ttt2.lua

Fixed an issue introduced by #1521
This happens because combo boxes can have values where the validity check fails (like strings).

Fix: Combobox Validity Check

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua

Gunshot sounds would get interrupted by the dryfire sound, sounding quite jank.
This has been fixed by making the dryfire sound use a different channel. Now the last shot in the magazine won't be silenced if you keep holding the trigger!
The parameters in EmitSound match the settings that the "Weapon_Pistol.Empty" soundscript would use (except the channel), so it sounds exactly the same pitch and volume wise.

Weaponbase: Fixed weapon dryfire sound interrupting gunshot sounds

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/client/cl_voice.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/shared/hud_elements/tttvoice/pure_skin_voice.lua
gamemodes/terrortown/gamemode/shared/sh_init.lua
gamemodes/terrortown/gamemode/shared/sh_main.lua
lua/ttt2/libraries/voicebattery.lua

The voice battery drain was previously removed from the UI in the voice rework. It is now added back to the UI. While doing so I moved all convars and functions to a new module called `voicebattery`. That way I was able to remove the global bools and replace them with with replicated convars.
I'm not sure that I'm a fan of the voice battery being client only. This seems like a bad idea to me. But I wanted to keep it that way for now, we might want to redo it at some point.

Voice Chat: Added module for battery drain and bar to UI

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/vgui/cl_sb_row.lua

Fixes #1483
When a player is dead and confirmed, you can see the search info in the scoreboard when clicking on their name. This did not work for players that died because they forced themselves as a spectator. This is because of this `if/else` structure that did not handle `GROUP_SPEC`.
As there only exists these four groups:
```lua
GROUP_TERROR = 1
GROUP_NOTFOUND = 2
GROUP_FOUND = 3
GROUP_SPEC = 4
```
I decided to just changes this to an `else`. The only sideeffect is that you are now able to click on any spectator in the scoreboard and it says that this player has no search information available. To me this seems like a valid solution.

Scoreboard/Specs: Changed Groups for Scoreboard Search

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_basegrenade_proj.lua
gamemodes/terrortown/entities/entities/ttt_firegrenade_proj.lua
lua/ttt2/libraries/game_effects.lua

Fixes #1427
This pullrequests fixes the issue with incediaries not spawning fire particles (or spawning them in the next room if there is any) when exploding close to a wall. The relevant change for this fix is in the base grenade file:
This is not a TTT2 issue, it also [exists in vanilla TTT](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/terrortown/entities/entities/ttt_basegrenade_proj.lua#L54). The issue exists because the trace, that should detect the ground, does not ignore the grenade itself and returns therefore a kind of random HitNormal. Since the grenade is then moved along the normal prior to explosion, this often resulted in the grenade being behing a wall and therefore not spawning any particles.
Adding `self` to the filter would fix this issue as …

Incendiary: Fixed explosion sometimes missing fire

---

CHANGELOG.md

We never pulled the changelog changes for the v0.13.2b release back to our master branch.
This is now fixed so that the Changelog file is now accurate again.
PS: This PR also includes some automatic formatting changes

docs(Changelog): Add v0.13.2b and move relevant changes to it

---

lua/ttt2/libraries/gameloop.lua

This PR switches from `gameloop.roundState` back to `GAMEMODE.round_state`. This is done for two reasons:
- it is compatible with addons that try to access this variable directly
- it is hotreload safe because the table is kept on reload

Gameloop: Switched Back to GAMEMODE Table for RoundState

---

gamemodes/terrortown/gamemode/shared/hud_elements/tttvoice/pure_skin_voice.lua

Fixed the new voicehud's embossing effect overlapping the profile picture

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_zm_improvised.lua

Minor visual fix
Swinging your crowbar in thirdperson would have no animation (everyone else sees it fine). This PR fixes that for both primary and secondary attack

Weapons: Fixed crowbar attack animation not being visible to the local player

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
gamemodes/terrortown/entities/weapons/weapon_zm_shotgun.lua

- Added SWEP.DryFireSound to the weapon base to allow the dryfire sound to be easily changed (now used by the shotgun)
- Applied dryfire sound fix to the shotgun
- Allowed the shotgun to attempt reloading on dryfire
- Interrupting the shotgun's reload looks and feels less jank
- Added a third person reload animation to the shotgun
Side note: while making these changes, I only now realised that the dryfire sound only plays for the player holding the weapon. I think this is fine but I thought I would ask, should we instead let the sound be audible to anyone near the player? I can make another PR if so

Weapons: Shotgun changes

---

gamemodes/terrortown/gamemode/client/cl_voice.lua

Fixed the issue that the spectator voice duck amount setting wasn't working as expected because of a typo in the convar name.

fixed spectator voice duck convar typo

---

lua/ttt2/libraries/admin.lua

Replaced false with REVIVAL_BLOCK_NONE to prevent the following deprecation warning when you try to respawn someone from the new admin menu:
```
[ttt2] [DEPRECATION WARNING]: You should use the REVIVAL_BLOCK enum here.
1. Revive - addons/ttt2/gamemodes/terrortown/gamemode/server/sv_player_ext.lua:849
2. PlayerRespawn - addons/ttt2/lua/ttt2/libraries/admin.lua:129
3. func - addons/ttt2/lua/ttt2/libraries/admin.lua:230
4. unknown - lua/includes/extensions/net.lua:38
```

using revival block to prevent deprecation warning

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua

This fixes the following issue:
```
[TTT2 (Base) - v0.13.2b] gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua:95: attempt to call method 'DropDevice' (a nil value)
1. PreDrop - gamemodes/terrortown/entities/weapons/weapon_ttt_cse.lua:95
2. DropNotifiedWeapon - gamemodes/terrortown/gamemode/server/sv_weaponry.lua:626
3. unknown - gamemodes/terrortown/gamemode/server/sv_player.lua:730
```
This issue was caused because the DropDevice function doesn't exist anymore. It was removed here: https://github.com/TTT-2/TTT2/commit/b83216e0fedf1454e31f54cffd9f340a3d082600#diff-4e2900ec902da3fc854104b03d5e314aa0187a1cae52fd7a2ccdd9d782b64434L102
I tested it and it works. The visualizer drops on death without creating an error.

fixed nil error

---

gamemodes/terrortown/gamemode/client/cl_voice.lua

`GM:PlayerEndVoice` was resetting players' team voice state even if they were still talking in team voice chat because `GM:PlayerEndVoice` is called client-side whenever a player stops audibly talking (not when they are actually done using voice chat). This was unnecessary anyway so I removed the hook.
There were also multiple issues related to stuff not being updated on round start / team change (panel colors not being updated and your panel being shown but you weren't actually speaking). The simplest solution I found was forcibly re-enabling voice chat on team change.
Unfortunately I discovered that using 0s timers for re-enabling voice chat is inconsistent for whatever reason and wouldn't always call `GM:PlayerStartVoice`.
I didn't fine-tune the timing but using 0.05s (2 or 3 ticks?) …

Voice: fix panel colors and voice chat not working after round start

---

gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
lua/terrortown/entities/items/item_ttt_disguiser.lua
lua/ttt2/libraries/bodysearch.lua

Fixes #1565.
Small language and textbox improvements.

Lang: Fixes and Improvements

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/sh_marker_vision_element.lua

Fixes #1477 by making sure that the whole team is only notified if the player knows about their team mates.

Markervision: Fix Unknown Teams

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_spawneditor.lua
gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua
lua/terrortown/lang/en.lua
lua/ttt2/extensions/input.lua

Fixed #1571
Made sure that undefined bindings do not cause errors. While I was at it, I replaced the hardcoded fallbacks with "UNK" (undefined key) so the user is less confused when nothing happens

Bindings: Fixed Undefined Bindings Breaking Gamemode

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua

The old implementation double inverted the value, when pressing reset, resulting in inverted outputs.

Equipment Editor: Fix Inverted

---

lua/ttt2/libraries/gameloop.lua

Most mapvote addons work by overwriting the `LoadNextMap()` function. However in a recent rework, the TTT2 gameloop got completely reworked which broke that way of hooking into it.
The easiest solution here is to add a fallback mode that calls the overwritten function if defined. This is done here. Additionally I raise an error to make sure the server owner is aware of the problem.
When this function is called, the next map condition is already met. And since these functions are all based on the old TTT function, the condition will still be met inside it, even if the round counter is decreased by one more. Therefore we don't have to modify any values here.
By doing it that way it is pretty clean and safe to call deprecated map vote trigger functions, without hacking too much into the TTT2 …

MapVote: Readded compatibility with old mapvote addons

---

gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

Fixed an issue @sbzlzh noticed where there are errors on color access in the first round. Strangely this only happens if it is the first round and ROLE_NONE. This fix looks kinda hacky imho, but the issue here seems to be rooted way deeper. I think it has probebaly something to do with our role syncing and that the default is alredy ROLE_NONE, so a role change is never triggered.
Moreover the same hacky solution was already implemented for the default role color call. In my opinion this solution is fine, but we should keep this issue in mind in case we refactor the role syncing at some point.
This issue also probably existed since our introduction of ROLE_NONE. Nobody noticed it, because the default player amount is 2. And with two players, there are roles assigned.

Player/Roles: Added Fallback Colors

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/hud_elements/tttsidebar/old_ttt_sidebar.lua

When adding translation support to sidebar info elements, it was forgotten to also add it to OldTTT. This is now fixed.

Sidebar: Added translation to OldTTT

---

CHANGELOG.md
lua/autorun/client/b-draw_lib.lua
lua/ttt2/libraries/gameloop.lua

Avatar icons are no longer fetched from Steam and are being created via [AvatarImage](https://wiki.facepunch.com/gmod/AvatarImage) instead.
The icon should appear much faster than before and therefore the player will always see an icon. (The fetching from Steam took a while and it was possible to see the default icon instead before the real avatar icon was shown.)
Should also solve the issue which some players from China had because Steam is blocked there.
Tested it on v0.14 and it seemed to work great (saving/loading also works).

Fetch: Removed fetching avatar icons from Steam

---

lua/ttt2/libraries/gameloop.lua
lua/ttt2/libraries/loadingscreen.lua

As requested on Discord I added a minimum render time, by default it is 4 seconds. For now you can't change it via convar, you have to call `loadingscreen.SetDuration` to edit that.
Moreover I cleaned up the rendering of the loadingscreen, mostly by improving the blurry-ness

Loadingscreen: Cleanup

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_player_ext.lua
gamemodes/terrortown/gamemode/server/sv_player_ext.lua
gamemodes/terrortown/gamemode/shared/sh_player_ext.lua

As discussed with @mexikoedi, I made `GM:TTT2PlayerReady` fully shared to be used in his #1600 PR. This might cause issues with third party addons, but at least for our addons, the change is fine. And I'm pretty sure nobody else is using that hook anyway.
To test:
- is `GM:SetupMove` only called for the local player on clients? I think so, but it has to be confirmed
- does this work at all?
- is every player on the client marked as ready, no matter the order in which the players connected?

PlayerReady: Extended Syncing

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_main.lua
gamemodes/terrortown/gamemode/client/cl_player_ext.lua
lua/autorun/client/b-draw_lib.lua

Avatar icons are now being refreshed.
It works like this:
If you don't have any icons saved then new ones will be created, cached and used.
Otherwise the already existing icons will be deleted, then they will be created, cached and used.
So if the player changes his avatar icon the already existing ones will be replaced with the new one.
Tested it on v0.14 and it seemed to work.
(The part with the "exists" is not needed anymore because they are always cached or they don't exit.)

Fetch: Fixed refreshing of avatar icons

---

gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/server/sv_player_ext.lua
gamemodes/terrortown/gamemode/shared/sh_entity.lua
lua/ttt2/libraries/buttons.lua

This pullrequest introduces a further fix to buttons that were introduced by the move of use calls to the client. It fixes the same issue the last PR (#1580) attempted to fix, but this time it improves upon this. Two things are done in this PR:
- added `foundButton:SetSolid(SOLID_BSP)` to make sure all buttons on the map can be actually hit by a trace. This also fixes the issue introduced in the last PR, where some buttons now had a hitbox the player could collide with
- rewrote the syncing to the client as it was a nightmare. Many entites are NULL entities on the client if the player is too far away. This new approach with NWInts fixes this because it makes use of the internal GMod systems.

Buttons: Further Fixes

---

gamemodes/terrortown/gamemode/client/cl_keys.lua
lua/ttt2/libraries/targetid.lua

Changed trace mask to `MASK_ALL`. I did the same for targetID, so that it reliably shows the targetID as well. Seems to fix all issues for minecraft based maps.

Buttons: Changed Trace Mask

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player.lua

Added a cancelable hook that is triggered on button use. This is needed for an addon that I want to create that adds further info to buttons (like a description of the button depending on its state)
```lua
---
-- A hook that is called before a button is pressed. Can be used to cancel the event by returning false.
-- @param Player ply The player that pressed the button
-- @param Entity ent The button entitiy
-- @param boolean oldState The old toggle state of the button before it was pressed
-- @return boolean return false to prevent the player from using that button
-- @hook
-- @realm server
function GM:TTT2OnButtonUse(ply, ent, oldState)
```

Buttons: Added Cancelable Hook

---

lua/terrortown/lang/en.lua
lua/terrortown/menus/gamemode/administration/roundsetup.lua
lua/terrortown/menus/gamemode/appearance/general.lua
lua/ttt2/libraries/loadingscreen.lua

Added enabling and duration settings to the server settings panel because I already see loads of players complaining. This way I have the peace of mind.

Loadingscreen: Added Serverside Settings

---

CHANGELOG.md
lua/ttt2/libraries/buttons.lua

Added a hook that is called AFTER all buttons on the map are initialized. This happens on hotreload and post map cleanup. I added this hook because I need it in my button name addon so that I don't have to rebuilt the existing list again.
```lua
---
-- Hook that is called after all buttons were initialized on the map. This happens after
-- a map cleanup when a new round starts or when the list is rebuilt after a hotreload.
-- @param table buttonList A table with all buttons found on the map
-- @hook
-- @realm server
function GM:TTT2PostButtonInitialization(buttonList)
```

Buttons: Post Button Init Hook

---

gamemodes/terrortown/gamemode/client/cl_keys.lua
gamemodes/terrortown/gamemode/server/sv_entity.lua
gamemodes/terrortown/gamemode/server/sv_player.lua
lua/ttt2/libraries/targetid.lua

Since there were still issues with clientside use detection (at least on the map `ttt_mc_jondome` one button refused to work), I added a serverside fallback. If the client doesn't detect any entity on use press, the server uses the engine function to detect any use entity close by. This works.
Only downside is that it triggers uses for entities where the targetID is just slightly out of range. However this is how it has been in 0.13.2 and earlier as well.
Update: In the last commit I implmented `IsUsableEntity` from the sourceSDK in lua. All important links to the original code are in the added code. I had to do this because enties without a `+use` assigned could block the trace. Now it uses the aforementioned serverside fallback if an entity has no use. …

Buttons: Added Serverside Fallback

---

gamemodes/terrortown/gamemode/client/cl_targetid.lua

Recently a user on discord had problems with an error that was spammed. It was because a faulty addon tried to draw the OHI without a valid player. To ensure that the game is still playable, I added a simple validity check here.
Should be merged before the release PR.

OverHeadIcon: Add Safeguard Check

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_changes.lua
gamemodes/terrortown/gamemode/client/cl_main.lua

This pullrequest fixes the issue where items (not weapons) had the wrong state if a custom show was created. This means that they were always marked as selected, even if they weren't. This was due to the caching being done too early, before the items were initialized at all.
The issue didn't exist for weapons because their setup is done in the engine before any lua init code is executed.

Shopeditor: Item Buyability Broken due to Cache State

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_popups.lua

This PR fixes #1631 . 
I tested it and the missing translation error for the None role doesn't appear anymore.

Translation: Fixed missing translation for None role error

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_voice.lua

This PR fixes #1629 .
I tested it and the missing translations for Terrorists and Spectators if you try muting them with F2 are now working correctly.

Translation: Fixed translation of muting terrorists and spectators

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_base_placeable.lua
gamemodes/terrortown/entities/entities/ttt_hat_deerstalker.lua
gamemodes/terrortown/entities/entities/ttt_health_station.lua
gamemodes/terrortown/gamemode/server/sv_entity.lua

This fixes #1634 and #1635
The issue this PR fixes is that previously the fallback was called for all SENTs (scripted entities) because they lack any engine related use flags. Therefore the clientside trace was completely ignored for this kind of entity.
I added support for our SENTs to `entmeta:IsUsableEntity`. This might look a bit hacky, but let me explain:
- First, the obvious, if an entity has `.CanUseKey` set to true, it has a use functionality attached. This is a good check, because this is a flag that was needed in vanilla TTT as well, so it has good compatibility.
- Second, there are special cases for weapons and ragdolls. This is a bit hacky indeed. However it is handled the same way in the server use handler, so I guess it is fine

Lua ent use fix

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_hud_manager.lua

Fixes #1630
Fixes the loadingscreen rendering issues that appeared because no true 2D rendering context was provided. This now also means that everything is blurred, even vgui. I think that is fine.
It would be nice if @mexikoedi could confirm that this also fixes the issue on his PC.

Loadingscreen: Render Hook Change

---

CHANGELOG.md
lua/ttt2/libraries/targetid.lua

This replaces the usage of the ttt specific `ttt_driver` NWEntity with the
base gmod `Vehicle:GetDriver` [1] function to determine the driver of a
targeted vehicle.
The ttt solution of keeping track of a vehicle's driver via a networked Entity
on the vehicle has existed since forever (12+ years). So i'm sure it has had
its reasons to exist.
But for at least 5 years base gmod has had the ability to get the driver of a
specific vehicle so this should be the way we determine this going forward.
I would love to rip the whole `ttt_driver` NWEntity out of the code completely.
Not only because we definitely have better ways of handling this without
increasing networking churn, but also because setting the driver to the vehicle
itself, when the driver exits the vehicle, is questionable at best. …

refactor(targetid): Use `Vehicle:GetDriver` instead of NWEntity

---

CHANGELOG.md
lua/terrortown/lang/en.lua
lua/terrortown/lang/ru.lua

- Russian:  Translated new strings and the updated one.
- English: loadingscreen → loading screen.

Localization: updated Russian and English localization files

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_weaponry.lua

Add check for trace start solid to prevent teleporting weapon through walls.
Edgecases can occur where weapons can be picked up through walls (even thick 16 unit walls didn't prevent this). This is because the trace can start solid (most likely if the weapon is too large for the space its resting, in my case a relatively small func_detail shelf) and then the tr.Fraction will return 1.0 through a solid wall, causing weapons the be teleported and picked up.

Fix weapon pickup through walls

---

CHANGELOG.md
lua/ttt2/libraries/thermalvision.lua

A check was added to prevent spectators from being displayed with thermal vision. This is relevant in cases where players are highlighted by TV and then killed, as they are not automatically removed from the entity list. Also prevents SpecDM players from being seen.

Spectators no longer visible in thermalvision

---

CHANGELOG.md
lua/terrortown/lang/ko.lua
lua/terrortown/lang/tr.lua

It's not complete translation, but it's translated enough to play.
I made it for users who play TTT2 in Korea.

Language: Add Korean translation.

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/hud_elements/tttinfopanel/old_ttt_info.lua

This is a feature from the original TTT reimplemented in TTT2.

HUD: Show name of spectated player in old TTT HUD

---

CHANGELOG.md
lua/ttt2/libraries/map.lua

Updated changes after a few iterations are now the following:
* Unconditionally create gm, ttt and ttt2 prefixes
We can reasonably assume `gm` maps to be present on the server, the same
goes for `ttt` and `ttt2` maps.
Creating convars dynamically if we find more map prefixes is still
done. And only prefixes for installed maps will be shown anyway.
* Disable all map prefixes but `ttt` and `ttt2` by default
We will assume people only want to run maps intended for ttt(2).
Given that the prefix selection can be modified on the same admin
settings page that is (currently) the only one using these convars this
seems fine.
* Drop FCVAR_NOTIFY for all `map_prefix_enabled` convars
Given that these are purely used in an admin context there is no need to
announce changes to all users on the server. …

fix(map): Streamline behaviour for the ttt2_enable_map_prefix_ convars

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_zm_carry.lua

Adds working C_Hands to the magneto stick so it not longer uses the default HEV suit hands
(accidentally deleted the first pull request because idk how github works all the way yet sorry)

Magneto Stick C_Hands

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player_ext.lua

When trying to drop ammo on a weapon with no AmmoEnt (aka AmmoEnt = ""), an error appears in the console from trying to create a non-existent entity.

Fixed error when trying to drop ammo for weapons without AmmoEnt

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_beacon.lua

fix(beacon): Use translation for entity instead of hardcoded name

---

CHANGELOG.md
lua/terrortown/lang/en.lua
lua/ttt2/libraries/targetid.lua

Before this change when looking at a corpse targetID would show the same hint whether `ttt_identify_body_woconfirm` was enabled or not.
This change introduces a new language string that does neither mention corpse confirmation nor searching covertly.

fix(targetid): Respect enabled `ttt_identify_body_woconfirm`

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_main.lua

This fixes #1648 in cases where not all entities have been initialized for a client.

fix(cl_main): Prevent client lua error

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_corpse.lua
gamemodes/terrortown/gamemode/server/sv_main.lua
gamemodes/terrortown/gamemode/shared/sh_corpse.lua
lua/autorun/gs_crazyphysics.lua
lua/ttt2/libraries/bodysearch.lua
lua/ttt2/libraries/targetid.lua

In #1684, `targetid.HUDDrawTargetIDRagdolls` was updated to check if the `ttt_idenfity_body_woconfirm` ConVar was enabled to determine what hint gets displayed.
Problem is, this ConVar only exists on the server, and the TargetID library is entirely clientside. This resulted in Lua errors being thrown on every frame the function was called and managed to reach that check.
~~This PR adds a GlobalBool and ChangeCallback for `ttt_idenfity_body_woconfirm`, and updates the check to use it instead of a nonexistent ConVar object. It also adds a ChangeCallback for `ttt2_confirm_team`, and changes its initial `SetGlobal` call to grab its name from its ConVar object to be consistent with the other GlobalVars in `SyncGlobals`.~~
This PR adds an additional table to the `CORPSE` namespace for the …

TargetID: Make `ttt_idenfity_body_woconfirm` replicated; move and clean up additional ConVars surrounding corpses/ragdolls

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player_ext.lua

Ammo dropping from the reserve was a bit weird. You currently drop `Min(Clipsize, Reserve)`, which is fine for default weapons where clip size = box ammo, but for any custom weapon with less ammo, things get increasingly weird.
The worst-case scenario involves weapons with super-low ammo. Consider the often-used pocket rifle, which has only a clip size of 1; here, you must drop ammo 10 times to drop the same as a regular 357 box.
My change makes it so that instead, you now drop `Min(Box Size, Reserve)`, which feels much better and has no downsides I can see. Dropping from the clip remains unchanged as it should.

Ammo Drop from reserve now tries to drop a full box, instead of, at most, a full clip

---

CHANGELOG.md
gamemodes/terrortown/entities/entities/ttt_base_placeable.lua

We call `LANG.Msg` on the client which doesn't use the first parameter to address a player. This shifts all the parameters to the wrong places.
Fixes #1695

fix(base_placeable): Prevent error on pickup fail

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_ttt_binoculars.lua

I've tested this with `net_fakelag 400` and boy does it make a difference.
Additionally this should fix #1625 by doing a sanity check of the binoculars owner before setting the owners FOV.

fix(binoculars): Allow zooming to be predicted

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_corpse.lua

The new corpse searching sounds play when anything searches them in any manner. The main example being spectators - if a spectator examined a body, the body would make a sound seemingly out of nowhere for players who are alive.
Covert searches and long range searches also cause the search sound to play which seems wrong.
The change in this PR fixes that. The sound will now only play if the player is alive (using IsTerror), and if the search wasn't covert or long range.

Fix: Prevent spectators, covert, and long range corpse searches from making sound

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_keys.lua

There's an alternative zoom command "toggle_zoom" which PlayerBindPress doesn't check for.
This command is now supported and triggers the radio commands menu like the regular +zoom command does.

Binds: Added support for "toggle_zoom" binds to trigger the radio commands menu

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_voice.lua

The VOICE library function that updates whether someone should be muted has a typo - it's trying to use "SetMute" rather than "[SetMuted](https://wiki.facepunch.com/gmod/Player:SetMuted)". This simply fixes the typo so muting works again.

Fix: Fixed the mute button in the scoreboard not working

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player.lua

This hook allows to change the sound of the deathscream or cancel it outright.
Maybe I'm mistaken but I thought the table approach would be the most appropriate one here. Please correct me if not.
Changelog will follow when this is done.

Hook: Added hook "TTT2PlayDeathScream" for deathscreams

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_shop.lua

fix(shop): Error messages tried to print player userdata

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_propspec.lua
gamemodes/terrortown/gamemode/shared/sh_cvar_handler.lua
lua/ttt2/libraries/keyhelp.lua

This PR would "fix" https://github.com/TTT-2/TTT2/issues/1706
I'm just not sure: Is using globals here a good idea? I though about using a replicated cvar, but that would require at least a cl_propspec.lua file to be added.
Changelog will follow when finished.

UI: Hide Propspec bind if disabled

---

CHANGELOG.md
lua/ttt2/libraries/marker_vision.lua

I discovered that when new marker vision objects are made with `markerVision.Add`, it doesn't clear out existing versions of the same object (matching ent and indentifier). This leads to the `markerVision.registry` table being filled up with objects that do not clear themselves, and makes `markerVision.Get` potentially return obsolete markers (mainly observed serverside).
This PR resolves this possible bloat issue in the registry. This also fixes an issue where marker vision objects can incorrectly change to being visible to team or visible to role (clientside), when it's supposed to be visible to everyone.

Markervision fix: Fixed registry table being able to have duplicates

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_player_ext.lua

now references the already created ammo box instead of trying to get data from via weapons ammo entity reference which can return nil.

Fixed error in new Ammo drop

---

gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dbutton_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dcheckboxlabel_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dlabel_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/droleimage_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dsubmenulist_ttt2.lua

This PR adds no new code or new functionality, it only moves code around in files so that everything that inherits from buttons can use (server) convars. Therefore the code from the ttt2 checkboxlabel was moved to button. This caused this change to track the underlying button in those labels:
Moreover I added our tooltip code from the panel to the label as well, as both of these are a starting point for the inheritance that can't be merged.
I'd appreaciate a quick merge so that #1715 can be finished.
Also note, that there are MANY things that could be further improved by improving the inheritance. This only tackles a small part of that.

vgui: Reworked inheritance

---

gamemodes/terrortown/gamemode/client/cl_vskin/vgui/drolelayeringreceiver_ttt2.lua

Layered roles were not toggleable upon menu rebuilt.

RoleLayering: Fixed layered roles not having working toggle

---

gamemodes/terrortown/gamemode/server/sv_player.lua

Switch 1 line to make the param ordering of GM:TTT2GiveFoundCredits(ply, rag) in the docs follow the ordering of the actual function.

Fix the ordering of param declarations

---

lua/terrortown/events/finish.lua

In #1733 I said in a review comment that the fallback can be removed here: https://github.com/TTT-2/TTT2/pull/1733#discussion_r1923652492
However, this was not true. I misread the context of the code. This caused the issue reported in #1744.

Fixed Win-Score Breaking Roundend Screen

---

gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dbutton_ttt2.lua
gamemodes/terrortown/gamemode/client/cl_vskin/vgui/drolelayeringreceiver_ttt2.lua

fixes #1735
This issue was created since the cvar is now tracked in the "main button" not the checkbox button anymore. This worked fine for serverside settings with custom handling, as well as client settings that use function wrappers to set the convar (like vskin for example).
This change now correctly sets the stored convar. It feels a bit hacky to me to be honest, but only a full rewrite would resolve this. So it is probably fine.
I also noticed that [this requested change](https://github.com/TTT-2/TTT2/pull/1724#discussion_r1921642625) was not applied to all function calls, so I renamed the one remaining.
Last but not least, I noticed that the border radius was substracted twice.

vGui: Fixed Clientside ConVars & Small Misc Fixes

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_ttt_m16.lua

This aligns the iron sights position of the m16 to fit better and lessens the zoom on the iron sights to look at a lot better, the little default zoom I feel is a little much.
Before 
After

M16 Ironsights Allignment and Zoom Tweak

---

CHANGELOG.md
lua/ttt2/libraries/outline.lua

Its finally here, the rework of the outline library which started because of https://github.com/TTT-2/TTT2/issues/1411
Ive spent quite some time on this trying over 50 different approaches, running into various setbacks each time.
Some of them got solved: https://github.com/Facepunch/garrysmod-issues/issues/5744
And some didnt: https://github.com/Facepunch/garrysmod-requests/issues/2308
But this is what i consider the best thats possible in gmod today in respect to functionality and performance.
This rework includes(i may have forgotten some, its been a while):
- A switch to using the zbuffer instead of line of sight checking every single entity
- Outline thickness option
- Multiple render types for outlines
- More performant drawing
- Drawing not breaking when scopes are used in weapon …

Rework the outline library and fix the outstanding issues with it

---

CHANGELOG.md
lua/ttt2/libraries/outline.lua

Current behavior:
This is simply due to not updating the stencil when the Z-test passes

Fix OUTLINE_MODE_BOTH and OUTLINE_MODE_VISIBLE

---

CHANGELOG.md
gamemodes/terrortown/gamemode/server/sv_addonchecker.lua

The addon (https://steamcommunity.com/sharedfiles/filedetails/?id=2795122660) is no longer supported too and seems to cause some issues with TTT2. For example: How corpses are created is overwritten and causes them to act like they are fake.

Added incompatible addon to the addonchecker

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/hud_elements/tttpickup/pure_skin_pickup.lua

This fixes Hud errors when picking up an item or weapon with no viable icon by falling back to the item_special icon
Fixes https://github.com/TTT-2/TTT2/issues/1728

Fixed Hud error on pickup

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_changes.lua
gamemodes/terrortown/gamemode/shared/sh_init.lua

This adds the changelog & bumps the version for 0.14.3

[Release] 0.14.3

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_equip.lua

This fixes the shop search breaking when using certain special characters because of luaPatterns
Fixes https://github.com/TTT-2/TTT2/issues/1800

Fixed shop search

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_chat.lua

This PR adds a fix from here: https://github.com/Facepunch/garrysmod/commit/38b7394ced29ffe318213e580efa4b1090828ac7
The issue which is solved by the fix is described here: https://github.com/Facepunch/garrysmod-issues/issues/6246

Fixed a regression in TTT voice chat team colors

---

CHANGELOG.md
gamemodes/terrortown/entities/weapons/weapon_tttbase.lua

Sometimes, random pieces of viewmodels (arms, floating guns) would appear briefly during rounds. Today, I noticed I was able to reliably trigger the bug by making a mimic bot use ironsights while looking towards the center of the map.
I couldn't find exactly what the root cause was, but I did find it was the LocalPlayer's viewmodel entity briefly rendering another weapon...
This PR patches out the issue. Spectating players in first-person still works fine.
Demo of the bug (I'm spamming right-click to make the bot use ironsights):
https://github.com/user-attachments/assets/49c7dfa0-4823-47f5-95be-4858198b9e7d

Fixed ghost viewmodels briefly appearing from weapons held by other players

---

CHANGELOG.md
gamemodes/terrortown/gamemode/shared/sh_door.lua

This PR fixes #1813 .
I tested it and I couldn't reproduce the error from the above issue again.

Fixed null physics object error for doors

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_keys.lua

Currently, trying to use entities and pick up weapons through water and clip brushes doesn't work, even though your TargetId HUD says you can.
This was happening because the clientside trace was using MASK_ALL. I've now changed to MASK_SOLID + CONTENTS_DEBRIS, which is roughly the same mask that the TargetId HUD uses.
I'm aware #1821 exists which I assume would fix this problem when it's eventually merged in, but I thought I would patch this issue specifially while that PR is still in the works.

Fixed not being able to use entities through water and clip brushes

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_search.lua
gamemodes/terrortown/gamemode/client/vgui/cl_sb_info.lua
lua/ttt2/libraries/bodysearch.lua

Today, I tried creating custom bodysearch entries using `GM:TTTBodySearchPopulate` and found that it didn't seem to be possible without changing the gamemode's code.
This commit contains the changes I made to fix it, along with improvements such as letting custom bodysearch entries access features that built-in ones have (icon text, background color). The changelog details everything I've done.

Bodysearch: Improvements and fixes to the GM:TTTBodySearchPopulate hook and how its data is handled

---

CHANGELOG.md
gamemodes/terrortown/gamemode/client/cl_targetid.lua

You can modify the target entity, but the distance value would remain the same since it couldn't be changed. This can make targetids to appear and disappear unexpectedly if the target entity was changed.
I've made `GM:TTTModifyTargetedEntity` read a second return value for distance so devs can correct the distance or do as they please with it. I've checked and it doesn't let you use entities from far away if you force target them with distance set to 0.

TargetId: Let GM:TTTModifyTargetedEntity modify the target distance

---

CHANGELOG.md
lua/ttt2/libraries/marker_vision.lua

This PR fixes #1834 .
The null entity error was introduced in #1825 .
I tested it and I couldn't reproduce the error from the above issue again.
Error reason:
markerVision.Remove is called twice.
The first time ent is valid but the second time it's a null entity and that caused the error.

Markervision: Fixed null entity error
